/**
 * P12 §7 — the validation report (docs/meta-validation.md).
 *
 * A human-readable QA artifact the maintainer eyeballs against guide sites
 * (~10 min/patch). Per character, per sequence (S0 + S6, plus any with
 * conditional thresholds): the three solo-mode priority orders, the top
 * normalized weights, ER-mode status, detected thresholds, and divergence
 * flags. Unresolved/notable entries are surfaced at the top.
 *
 * Pure: takes the in-memory meta object, returns markdown. Deterministic
 * (same meta → identical report, modulo the meta's own generatedAt).
 */

import { derivePriority, normalizePerRoll, perRollValue, statLabel } from '../../src/core/stat-priority.js';

// Sequences to print in detail (S0 + S6 per §7; cheap to add all if wanted).
const DETAIL_SEQUENCES = ['0', '6'];

function fmtPriority(weights, erMeta, mode, statRanges) {
    return derivePriority(weights, erMeta, mode, statRanges)
        .map(entry => statLabel(entry.key) + (entry.gate ? ` (${entry.note})` : (entry.note ? ` — ${entry.note}` : '')))
        .join(' › ');
}

function topWeightsTable(weights, statRanges) {
    const norm = normalizePerRoll(weights, statRanges, { excludeKeys: ['energyRegen'] })
        .filter(entry => entry.normalized > 0)
        .sort((entryA, entryB) => entryB.normalized - entryA.normalized)
        .slice(0, 4);
    const lines = ['| Stat | Relative (per-roll) |', '| --- | --- |'];
    for (const entry of norm) lines.push(`| ${statLabel(entry.key)} | ${entry.normalized.toFixed(0)} |`);
    return lines.join('\n');
}

// "Unusual" orderings worth the maintainer's eye (§7 divergence flags). Compared
// on per-roll value (the meaningful unit), not raw per-1% weight.
function divergenceFlags(weights, statRanges) {
    const flags = [];
    if (perRollValue('atkRatio', weights.atkRatio, statRanges) > perRollValue('critDmg', weights.critDmg, statRanges) && weights.critDmg > 0) {
        flags.push('ATK% outranks Crit DMG per roll — verify (unusual for a crit-built DPS)');
    }
    const dmgKeys = Object.keys(weights).filter(k => k.startsWith('dmgBonus.') && k !== 'dmgBonus.element');
    if (dmgKeys.every(k => weights[k] === 0)) {
        flags.push('no skill-type DMG bonus carries any weight — check the reference rotation covers the kit');
    }
    return flags;
}

export function buildValidationReport(meta, statRanges) {
    const markdown = [];
    markdown.push('# Meta Validation Report');
    markdown.push('');
    markdown.push(`Generated by \`tools/optimize.mjs\` (P12). Meta version ${meta.metaVersion}, `
        + `game ${meta.gameVersion}, engine \`${(meta.engineHash || '').slice(0, 12)}\`.`);
    markdown.push('Read top to bottom; ⚠ first. Spot-check the priority orders against a guide site.');
    markdown.push('');

    // ── ER-model banner (the §3a deviation, surfaced loudly) ──────────────────
    markdown.push('## ER model — read first ⚠');
    markdown.push('');
    markdown.push('ER is reported as a **mode choice**, not a single solo breakpoint '
        + '(maintainer direction 2026-06-27; see `tools/optimize/breakpoints.js`). A solo '
        + 'resonator builds Resonance Energy over many cycles from 0, so there is no '
        + 'within-rotation solo cliff to detect. Per-hit cast generation IS modeled '
        + '(including the Intro Skill\'s own flat Concerto restore, folded in 2026-07-10) — '
        + 'unless a kit explicitly states otherwise, Resonance Energy is NOT generated from '
        + 'taking damage or dodging (maintainer-confirmed 2026-07-10; only Concerto gains '
        + 'some from dodging), so that is not a modeled gap for most kits. '
        + '**Team-context** ER targets (the honest numbers) live in the team '
        + 'section below. Modes: **dmgFocus** (ignore ER), '
        + '**balanced** (target ~125%), **erFocus** (ER ranked only for ER-scaling kits).');
    markdown.push('');

    // ── Notable entries up top ────────────────────────────────────────────────
    const notable = [];
    for (const character of Object.values(meta.characters)) {
        const sequence0 = character.bySequence?.['0'];
        const firstSonata = sequence0 && Object.values(sequence0.bySonata ?? {})[0];
        if (firstSonata && firstSonata.erMode.scalesWithEr) notable.push(`${character.name} — ER-SCALING kit (ER carries real weight)`);
        if (firstSonata && !firstSonata.erMode.libCostKnown) notable.push(`${character.name} — Liberation not energy-gated (no ER requirement)`);
        for (const son of Object.values(sequence0?.bySonata ?? {})) {
            for (const flag of divergenceFlags(son.weights, statRanges)) notable.push(`${character.name} — ${flag}`);
        }
    }
    if (notable.length) {
        markdown.push('## Notable / verify ⚠');
        markdown.push('');
        for (const note of [...new Set(notable)]) markdown.push(`- ${note}`);
        markdown.push('');
    }

    // ── Team pass QA (P13 §10 hard-req #10: the practical loop for catching
    //    nonsense suggestions before they ship) ─────────────────────────────────
    const teams = meta.teams;
    if (teams?.byCharacter && Object.keys(teams.byCharacter).length) {
        const nameOf = (id) => teams.memberBuilds?.[String(id)]?.name ?? String(id);
        markdown.push('## Team suggestions (P13) — spot-check ⚠');
        markdown.push('');
        markdown.push('Validate 2–3 anchors against guide sites: do the comps match known-good '
            + 'teams (Tune Break cores, DPS+buffer+sustain)? **Team-level ER**: computed '
            + 'by a capped event simulation (team-energy.js — per-hit cast generation + '
            + 'the off-field 50% share, Resonance Energy capped at the Liberation cost) '
            + 'with no safety margin (the per-hit data is exact, not estimated). Kits that '
            + 'are not energy-gated, or whose requirement exceeds the credibility gate, '
            + 'show "balanced default" (the provisional 125%) instead of a fabricated '
            + 'number.');
        markdown.push('');
        for (const anchor of Object.keys(teams.byCharacter).sort((idA, idB) => Number(idA) - Number(idB))) {
            markdown.push(`### Anchor: ${nameOf(anchor)} (${anchor})`);
            markdown.push('');
            for (const team of teams.byCharacter[anchor]) {
                const label = team.members.map(nameOf).join(' + ');
                const tag = team.curated ? ` — curated${team.archetype ? ` (${team.archetype})` : ''}` : '';
                markdown.push(`- **${label}**${tag} — score ${team.score}, team DPS ${team.teamDps}`);
                if (team.reason) markdown.push(`  - why: ${team.reason}`);
                const erBits = Object.entries(team.erOverride ?? {}).map(([id, override]) =>
                    `${nameOf(id)} ${override.provisional ? 'balanced default' : `${Math.round(override.recommended * 100)}% (min ${Math.round(override.minViable * 100)}%)`}`);
                if (erBits.length) markdown.push(`  - ER: ${erBits.join(' · ')}`);
            }
            markdown.push('');
        }
    }

    // ── Per-character detail ──────────────────────────────────────────────────
    markdown.push('## Per-character detail');
    markdown.push('');
    for (const [id, character] of Object.entries(meta.characters)) {
        markdown.push(`### ${character.name} (${id})`);
        markdown.push('');
        markdown.push(`Reference rotation: \`${character.referenceRotation.join(' › ')}\``);
        markdown.push('');
        for (const seq of DETAIL_SEQUENCES) {
            const bySeq = character.bySequence?.[seq];
            if (!bySeq) continue;
            for (const [sonataId, entry] of Object.entries(bySeq.bySonata ?? {})) {
                const erMode = entry.erMode;
                markdown.push(`**S${seq} · sonata ${sonataId}** — ER: `
                    + (erMode.scalesWithEr ? 'scales with ER' : erMode.libCostKnown ? `target ~${Math.round(erMode.balancedTarget * 100)}%` : 'not energy-gated'));
                markdown.push('');
                markdown.push('- dmgFocus: ' + fmtPriority(entry.weights, erMode, 'dmgFocus', statRanges));
                markdown.push('- balanced: ' + fmtPriority(entry.weights, erMode, 'balanced', statRanges));
                markdown.push('- erFocus: ' + fmtPriority(entry.weights, erMode, 'erFocus', statRanges));
                markdown.push('');
                markdown.push(topWeightsTable(entry.weights, statRanges));
                markdown.push('');
                if (entry.conditionalThresholds?.length) {
                    markdown.push('Conditional thresholds:');
                    for (const threshold of entry.conditionalThresholds) {
                        markdown.push(`- ${threshold.stat} ${threshold.isPercent ? threshold.value + '%' : threshold.value} → ${threshold.unlocks} (${threshold.source})`);
                    }
                    markdown.push('');
                }
            }
        }
    }

    return markdown.join('\n').trimEnd() + '\n';
}
