/**
 * P12 §7 — the validation report (docs/meta-validation.md).
 *
 * A human-readable QA artifact the maintainer eyeballs against guide sites
 * (~10 min/patch). Per character, per sequence (S0 + S6, plus any with
 * conditional thresholds): the three solo-mode priority orders, the top
 * normalized weights, ER-mode status, detected thresholds, and divergence
 * flags. Unresolved/notable entries are surfaced at the top.
 *
 * Pure: takes the in-memory meta object, returns markdown. Deterministic
 * (same meta → identical report, modulo the meta's own generatedAt).
 */

import { derivePriority, normalizePerRoll, perRollValue, statLabel } from '../../src/core/stat-priority.js';

// Sequences to print in detail (S0 + S6 per §7; cheap to add all if wanted).
const DETAIL_SEQUENCES = ['0', '6'];

function fmtPriority(weights, erMeta, mode) {
    return derivePriority(weights, erMeta, mode)
        .map(e => statLabel(e.key) + (e.gate ? ` (${e.note})` : (e.note ? ` — ${e.note}` : '')))
        .join(' › ');
}

function topWeightsTable(weights) {
    const norm = normalizePerRoll(weights, { excludeKeys: ['energyRegen'] })
        .filter(e => e.normalized > 0)
        .sort((a, b) => b.normalized - a.normalized)
        .slice(0, 4);
    const lines = ['| Stat | Relative (per-roll) |', '| --- | --- |'];
    for (const e of norm) lines.push(`| ${statLabel(e.key)} | ${e.normalized.toFixed(0)} |`);
    return lines.join('\n');
}

// "Unusual" orderings worth the maintainer's eye (§7 divergence flags). Compared
// on per-roll value (the meaningful unit), not raw per-1% weight.
function divergenceFlags(weights) {
    const flags = [];
    if (perRollValue('atkRatio', weights.atkRatio) > perRollValue('critDmg', weights.critDmg) && weights.critDmg > 0) {
        flags.push('ATK% outranks Crit DMG per roll — verify (unusual for a crit-built DPS)');
    }
    const dmgKeys = Object.keys(weights).filter(k => k.startsWith('dmgBonus.') && k !== 'dmgBonus.element');
    if (dmgKeys.every(k => weights[k] === 0)) {
        flags.push('no skill-type DMG bonus carries any weight — check the reference rotation covers the kit');
    }
    return flags;
}

export function buildValidationReport(meta) {
    const md = [];
    md.push('# Meta Validation Report');
    md.push('');
    md.push(`Generated by \`tools/optimize.mjs\` (P12). Meta version ${meta.metaVersion}, `
        + `game ${meta.gameVersion}, engine \`${(meta.engineHash || '').slice(0, 12)}\`.`);
    md.push('Read top to bottom; ⚠ first. Spot-check the priority orders against a guide site.');
    md.push('');

    // ── ER-model banner (the §3a deviation, surfaced loudly) ──────────────────
    md.push('## ER model — read first ⚠');
    md.push('');
    md.push('ER is reported as a **mode choice**, not a single solo breakpoint '
        + '(maintainer direction 2026-06-27; see `tools/optimize/breakpoints.js`). A solo '
        + 'resonator builds Resonance Energy over many cycles from 0, so there is no '
        + 'within-rotation solo cliff to detect. Per-hit cast generation IS modeled; '
        + 'enemy-dependent generation (damage taken, kill orbs) is out of scope by design '
        + 'and the Concerto/intro economy is not yet modeled — so no solo cliff is '
        + 'fabricated. **Team-context** ER targets (the honest numbers) live in the team '
        + 'section below. Modes: **dmgFocus** (ignore ER), '
        + '**balanced** (target ~125%), **erFocus** (ER ranked only for ER-scaling kits).');
    md.push('');

    // ── Notable entries up top ────────────────────────────────────────────────
    const notable = [];
    for (const [id, c] of Object.entries(meta.characters)) {
        const s0 = c.bySequence?.['0'];
        const firstSonata = s0 && Object.values(s0.bySonata ?? {})[0];
        if (firstSonata && firstSonata.erMode.scalesWithEr) notable.push(`${c.name} — ER-SCALING kit (ER carries real weight)`);
        if (firstSonata && !firstSonata.erMode.libCostKnown) notable.push(`${c.name} — Liberation not energy-gated (no ER requirement)`);
        for (const son of Object.values(s0?.bySonata ?? {})) {
            for (const f of divergenceFlags(son.weights)) notable.push(`${c.name} — ${f}`);
        }
    }
    if (notable.length) {
        md.push('## Notable / verify ⚠');
        md.push('');
        for (const n of [...new Set(notable)]) md.push(`- ${n}`);
        md.push('');
    }

    // ── Team pass QA (P13 §10 hard-req #10: the practical loop for catching
    //    nonsense suggestions before they ship) ─────────────────────────────────
    const teams = meta.teams;
    if (teams?.byCharacter && Object.keys(teams.byCharacter).length) {
        const nameOf = (id) => teams.memberBuilds?.[String(id)]?.name ?? String(id);
        md.push('## Team suggestions (P13) — spot-check ⚠');
        md.push('');
        md.push('Validate 2–3 anchors against guide sites: do the comps match known-good '
            + 'teams (Tune Break cores, DPS+buffer+sustain)? **Team-level ER**: computed '
            + 'by the steady-state sweep (team-energy.js — per-hit cast generation + the '
            + 'off-field 50% share). Real targets are conservative upper bounds: '
            + 'enemy-dependent generation (damage taken, kill orbs) is out of scope by '
            + 'design, and the Concerto/intro economy is not yet modeled. Kits that are '
            + 'not energy-gated, or whose requirement exceeds the credibility gate, show '
            + '"balanced default" (the provisional 125%) instead of a fabricated number.');
        md.push('');
        for (const anchor of Object.keys(teams.byCharacter).sort((a, b) => Number(a) - Number(b))) {
            md.push(`### Anchor: ${nameOf(anchor)} (${anchor})`);
            md.push('');
            for (const t of teams.byCharacter[anchor]) {
                const label = t.members.map(nameOf).join(' + ');
                const tag = t.curated ? ` — curated${t.archetype ? ` (${t.archetype})` : ''}` : '';
                md.push(`- **${label}**${tag} — score ${t.score}, team DPS ${t.teamDps}`);
                if (t.reason) md.push(`  - why: ${t.reason}`);
                const erBits = Object.entries(t.erOverride ?? {}).map(([id, e]) =>
                    `${nameOf(id)} ${e.provisional ? 'balanced default' : `${Math.round(e.recommended * 100)}% (min ${Math.round(e.minViable * 100)}%)`}`);
                if (erBits.length) md.push(`  - ER: ${erBits.join(' · ')}`);
            }
            md.push('');
        }
    }

    // ── Per-character detail ──────────────────────────────────────────────────
    md.push('## Per-character detail');
    md.push('');
    for (const [id, c] of Object.entries(meta.characters)) {
        md.push(`### ${c.name} (${id})`);
        md.push('');
        md.push(`Reference rotation: \`${c.referenceRotation.join(' › ')}\``);
        md.push('');
        for (const seq of DETAIL_SEQUENCES) {
            const bySeq = c.bySequence?.[seq];
            if (!bySeq) continue;
            for (const [sonataId, entry] of Object.entries(bySeq.bySonata ?? {})) {
                const er = entry.erMode;
                md.push(`**S${seq} · sonata ${sonataId}** — ER: `
                    + (er.scalesWithEr ? 'scales with ER' : er.libCostKnown ? `target ~${Math.round(er.balancedTarget * 100)}%` : 'not energy-gated'));
                md.push('');
                md.push('- dmgFocus: ' + fmtPriority(entry.weights, er, 'dmgFocus'));
                md.push('- balanced: ' + fmtPriority(entry.weights, er, 'balanced'));
                md.push('- erFocus: ' + fmtPriority(entry.weights, er, 'erFocus'));
                md.push('');
                md.push(topWeightsTable(entry.weights));
                md.push('');
                if (entry.conditionalThresholds?.length) {
                    md.push('Conditional thresholds:');
                    for (const t of entry.conditionalThresholds) {
                        md.push(`- ${t.stat} ${t.isPercent ? t.value + '%' : t.value} → ${t.unlocks} (${t.source})`);
                    }
                    md.push('');
                }
            }
        }
    }

    return md.join('\n').trimEnd() + '\n';
}
