"""Extract the buffs that APPLY a negative status, and how many stacks each one
applies — the game's own answer to "how big is one application".

`extract_status_damage.py` reads what a status DOES per stack. This reads what
puts the stacks there. The system status buff (10011000 Glacio Chafe, 10021000
Fusion Burst, …) is the status itself; a kit applies it through an ordinary buff
carrying `ExtraEffectID 5` (apply-buff), whose `ExtraEffectParameters` are

    [<target mode>, <buff id>, <stack count>]

with the count omitted for a single stack, and the buff id repeated instead of
counted in a few rows ("10041000#10041000#10041000" = 3). 73 such buffs exist,
namespaced by owner: the first four digits are the resonator id.

## What this does NOT give you

The link from a SKILL to these buffs. `db_skill` holds 562 exploration rows,
not character skills, and an ASCII sweep of all 482 `db_*.db` files finds each
applier referenced only from `db_buff` itself (buff → buff). The grant lives in
the ability blueprints, outside the ConfigDB entirely. So WHICH cast inflicts is
derived from the kit text (`tools/preprocess/status-apply.mjs`) and this file is
the ceiling that derivation is checked against — a kit may not be read as
applying more stacks than the game defines an applier for.

Output: data/status-appliers.json (committed, like data/status-damage.json).

    python tools/extract/extract_status_appliers.py <fmodel-export-root>
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from configdb import ConfigDB    # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

APPLY_BUFF_EFFECT = 5

# Both variants of each status buff — the weaker …0000 row and the …1000 row a
# player actually inflicts (see extract_status_damage.py).
STATUS_BUFFS = {
    10010000: 'glacio_chafe',    10011000: 'glacio_chafe',
    10020000: 'fusion_burst',    10021000: 'fusion_burst',
    10030000: 'electro_flare',   10031000: 'electro_flare',
    10040000: 'aero_erosion',    10041000: 'aero_erosion',
    10050000: 'spectro_frazzle', 10051000: 'spectro_frazzle',
    10060000: 'havoc_bane',      10061000: 'havoc_bane',
}


def parameter_tokens(value):
    """ExtraEffectParameters come back as a list of '#'-joined strings."""
    out = []
    for item in (value if isinstance(value, list) else [value]):
        out.extend(str(item).split('#'))
    return [token.strip() for token in out]


def main(export_root):
    buffs = ConfigDB(export_root).read(
        'db_buff', 'Buff',
        fields={'Id', 'ExtraEffectID', 'ExtraEffectParameters', 'ExtraEffectCD',
                'ExtraEffectCdForTarget', 'ExtraEffectRequirements', 'ExtraEffectReqPara'})

    appliers = {}
    for buff in buffs:
        if buff.get('ExtraEffectID') != APPLY_BUFF_EFFECT:
            continue
        tokens = parameter_tokens(buff.get('ExtraEffectParameters') or [])
        targets = [STATUS_BUFFS[int(token)] for token in tokens
                   if token.isdigit() and int(token) in STATUS_BUFFS]
        if not targets:
            continue
        # Either the buff id is repeated once per stack, or a trailing count
        # says how many. Both shapes appear; neither one ever uses the other.
        trailing = tokens[tokens.index(next(t for t in tokens
                                            if t.isdigit() and int(t) in STATUS_BUFFS)) + len(targets):]
        count = next((int(token) for token in trailing if token.isdigit()), None)
        stacks = count if count is not None else len(targets)
        cooldowns = [value for value in (buff.get('ExtraEffectCD') or []) if value and value > 0]
        appliers[str(int(buff['Id']))] = {
            'status': targets[0],
            'stacks': stacks,
            'icdSeconds': cooldowns[0] if cooldowns else None,
            'requirement': (buff.get('ExtraEffectReqPara') or [None])[0],
        }

    payload = {
        '_doc': ('Buffs carrying ExtraEffectID 5 (apply-buff) that name a system negative-status '
                 'buff. `stacks` is the game\'s own per-application count; the first four digits '
                 'of the buff id are the owning resonator. Generated by '
                 'tools/extract/extract_status_appliers.py; do not hand-edit. This file says HOW '
                 'MANY, not WHICH cast — the skill grant is not in the ConfigDB (see the module '
                 'docstring).'),
        'appliers': dict(sorted(appliers.items(), key=lambda item: int(item[0]))),
    }
    out_path = os.path.join(ROOT, 'data', 'status-appliers.json')
    with open(out_path, 'w', encoding='utf-8') as handle:
        json.dump(payload, handle, indent=1, ensure_ascii=False)
        handle.write('\n')
    print(f'{len(appliers)} status appliers -> {out_path}')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
