"""Extract the game's affliction (negative-status) damage table.

`AbnormalDamageConfig` is the LevelModifier term in the negative-status damage
formula — the value `src/core/enemy-status.js` had reverse-engineered as the
single constant 3674 from three worked examples at level 90.

The table settles two things that file flagged as assumptions:

  1. It is identical across all six elements at EVERY level, so the
     "ASSUMED to also hold for other inflicters of the same status until
     disproven" caveat is now confirmed rather than assumed.
  2. It is a CURVE over levels 1-100 (11 -> 4082), not one number. The engine
     modelled only level 90, which is exactly the level the worked examples
     happened to use.

Output: data/abnormal-damage.json (committed, like data/bindata/*.json), so a
fresh checkout does not need the multi-GB client export to build.

    python tools/extract/extract_abnormal_damage.py <fmodel-export-root>
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from configdb import ConfigDB    # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ELEMENT_COLUMNS = [f'Abnormal100{n}' for n in range(1, 7)]


def main(export_root):
    rows = ConfigDB(export_root).read('db_AbnormalDamage', 'AbnormalDamageConfig')

    by_level, per_element_differs = {}, []
    for row in rows:
        values = [row[column] for column in ELEMENT_COLUMNS]
        if len(set(values)) != 1:
            per_element_differs.append((row['Level'], values))
        by_level[row['Level']] = values[0]

    if per_element_differs:
        # Not a crash: the engine would need a per-element table, and silently
        # collapsing to one column would be the wrong answer. Say so loudly.
        print(f'WARNING: {len(per_element_differs)} level(s) differ per element — '
              f'enemy-status.js assumes one value per level. First: {per_element_differs[0]}')

    out = {
        '_doc': 'AbnormalDamageConfig (LevelModifier for negative-status damage) from the '
                'game ConfigDB, keyed by the INFLICTING level. Identical across all six '
                'elements at every level. Generated by tools/extract/extract_abnormal_damage.py; '
                'do not hand-edit.',
        'elementIndependent': not per_element_differs,
        'byLevel': {str(level): by_level[level] for level in sorted(by_level)},
    }
    path = os.path.join(ROOT, 'data', 'abnormal-damage.json')
    with open(path, 'w', encoding='utf-8') as handle:
        json.dump(out, handle, indent=1)
        handle.write('\n')

    print(f'abnormal damage: levels {min(by_level)}-{max(by_level)}, '
          f'element-independent={not per_element_differs}, lv90={by_level.get(90)}')
    print(f'wrote {path}')


if __name__ == '__main__':
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
