"""Extract the game's affliction (negative-status) damage definitions.

Two things, both previously unknown to the sim:

1. **Which damage row each affliction is.** `db_damage` carries seven rows of
   `Type 10` / `FormulaType 9`, one per element plus a Glacio variant, and
   `AbnormalDamageConfig`'s columns (`Abnormal1001..1006`) are named after them:

       1001 aero (Aero Erosion)      1004 fusion  (FUSION BURST)
       1002 electro (Electro Flare)  1005 spectro (Spectro Frazzle)
       1003 glacio (Glacio Chafe)    1006 havoc   (Havoc Bane)
       1007 glacio variant

   Their own FormulaParams are empty — the row says WHAT to deal, not how much.

2. **The per-stack multiplier, which is KIT-SPECIFIC.** A buff that triggers
   affliction damage carries `ExtraEffectID 121` and an explicit
   `stacks#multiplier` table (multiplier in 1/10000). This is the piece
   `docs/NEGATIVE-STATUS-REFERENCE.md` §2c lists as "pending calibration" for
   Fusion Burst — it was never a single global constant, which is why observing
   one character never generalised.

   Aemeath's four Fusion Burst variants read straight onto her kit text:
       110% + 10%/stack   (base)
       310% + 10%/stack   (+200%)
       115% + 15%/stack   ← S2 "each stack of Fusion Trail removed provides a
                             15% DMG Multiplier increase to Fusion Burst"
       515% + 15%/stack   ← the same, +400% in Stardust Resonance
   all to 60 stacks, matching her S6 "max stack limit ... increased to 60".

Output: data/affliction-damage.json (committed, like data/bindata/*.json).

    python tools/extract/extract_affliction_damage.py <fmodel-export-root>
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from configdb import ConfigDB    # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Affliction damage rows are Type 10 with FormulaType 9.
AFFLICTION_TYPE, AFFLICTION_FORMULA = 10, 9
# The buff ExtraEffect that deals affliction damage on a stack-scaled multiplier.
AFFLICTION_EFFECT_ID = 121

ELEMENT_TO_STATUS = {
    1: 'glacio_chafe', 2: 'fusion_burst', 3: 'electro_flare',
    4: 'aero_erosion', 5: 'spectro_frazzle', 6: 'havoc_bane',
}


def parse_stack_table(text):
    """'1#11000|2#12000' -> {1: 1.1, 2: 1.2} (raw values are 1/10000)."""
    out = {}
    for pair in text.split('|'):
        stacks, _, value = pair.partition('#')
        if stacks.isdigit() and value.lstrip('-').isdigit():
            out[int(stacks)] = int(value) / 10000
    return out


def main(export_root):
    database = ConfigDB(export_root)

    damage = database.read('db_damage', 'Damage', fields={'Id', 'Type', 'FormulaType', 'Element'})
    rows = {}
    for row in damage:
        if row['Type'] != AFFLICTION_TYPE or row['FormulaType'] != AFFLICTION_FORMULA:
            continue
        rows[str(int(row['Id']))] = {
            'element': row['Element'],
            'status': ELEMENT_TO_STATUS.get(row['Element']),
        }

    buffs = database.read('db_buff', 'Buff',
                          fields={'Id', 'StackLimitCount', 'ExtraEffectID', 'ExtraEffectParameters'})
    multipliers = []
    for buff in buffs:
        if buff['ExtraEffectID'] != AFFLICTION_EFFECT_ID:
            continue
        params = buff['ExtraEffectParameters'] or []
        damage_id = next((p for p in params if p in rows), None)
        table_text = next((p for p in params if '#' in p), None)
        if not damage_id or not table_text:
            continue
        table = parse_stack_table(table_text)
        if not table:
            continue
        multipliers.append({
            'buffId': int(buff['Id']),
            # Buff ids are prefixed by their owning resonator.
            'resonatorId': int(str(int(buff['Id']))[:4]),
            'damageId': damage_id,
            'status': rows[damage_id]['status'],
            'stackLimit': buff['StackLimitCount'],
            'byStacks': {str(k): v for k, v in sorted(table.items())},
        })
    multipliers.sort(key=lambda entry: (entry['resonatorId'], entry['buffId']))

    out = {
        '_doc': 'Affliction (negative-status) damage from the game ConfigDB. `rows` maps each '
                'affliction damage id (Type 10 / FormulaType 9) to its element and our status key. '
                '`multipliers` are the per-stack DMG multipliers carried by the BUFFS that trigger '
                'that damage (ExtraEffectID 121) -- kit-specific, not one global table per status, '
                'which is why observing a single character never generalised. Generated by '
                'tools/extract/extract_affliction_damage.py; do not hand-edit.',
        'rows': rows,
        'multipliers': multipliers,
    }
    path = os.path.join(ROOT, 'data', 'affliction-damage.json')
    with open(path, 'w', encoding='utf-8') as handle:
        json.dump(out, handle, indent=1)
        handle.write('\n')

    print(f'affliction rows: {len(rows)} — ' + ', '.join(
        f"{did}={info['status']}" for did, info in sorted(rows.items())))
    print(f'stack-multiplier tables: {len(multipliers)}')
    for entry in multipliers:
        stacks = entry['byStacks']
        low = stacks.get('1')
        high = stacks[max(stacks, key=int)]
        print(f"  resonator {entry['resonatorId']} buff {entry['buffId']} -> {entry['status']}: "
              f"{low}x at 1 stack .. {high}x at {max(stacks, key=int)} (limit {entry['stackLimit']})")
    print(f'wrote {path}')


if __name__ == '__main__':
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
