/**
 * Rotation prerequisite rules — mechanics-aware gating for the rotation builder.
 *
 * Phase 10 introduces a per-character rule table describing which rotation
 * steps are *gated* behind other steps. In Wuthering Waves many skills are
 * only available after a precondition is met:
 *
 *   - State-gated: a skill is only usable "while in <state>", and that state
 *     is entered by casting some other skill (e.g. Carlotta's Fatal Finale is
 *     only available inside Twilight Tango, entered by her Liberation).
 *   - Resource-gated: a skill consumes a Forte gauge that must be built up
 *     first (e.g. Carlotta's Imminent Oblivion needs full Substance).
 *   - Form/stance-gated: an alternate basic-attack chain that only exists in a
 *     special mode (e.g. Hiyuki's Foreclaimed Self basics, Jinhsi's
 *     Incarnation basics).
 *
 * Design principles
 * -----------------
 * 1. NON-BLOCKING. These rules drive *warnings*, never hard prevention. WuWa
 *    rotations are intricate and players know their character better than a
 *    heuristic. The validator informs; the user decides.
 * 2. CURATED, not auto-parsed. The descriptions are too varied to parse
 *    reliably into correct dependency directions. This table is hand-authored
 *    from the clearest, highest-impact gates, and is designed to grow
 *    incrementally — adding a character is a localized, low-risk edit.
 * 3. DATA-REFERENCED. Rules reference real autoSkillMap keys (verified against
 *    the dataset) so a key rename surfaces immediately in the validator tests.
 *
 * Rule shape
 * ----------
 *   {
 *     skillKey:  string        — the gated step (autoSkillMap key)
 *     requires:  string[]      — keys that satisfy the gate; ANY one earlier in
 *                                the rotation satisfies it (logical OR)
 *     gate:      'state'|'resource'|'form'  — category, for the warning copy
 *     note:      string        — short human explanation shown in the warning
 *   }
 *
 * A rule is "satisfied" for a given rotation position if at least one of its
 * `requires` keys appears at an earlier index. If none do, the validator emits
 * a warning for that step.
 */

// =============================================================================
// Per-resonator rule table, keyed by resonator id.
// =============================================================================
//
// Only characters with clear, impactful gates are listed. Absence of a
// character means "no gating rules" — every step is always considered valid.

export const ROTATION_RULES = Object.freeze({
    // ── Carlotta (1107) ──────────────────────────────────────────────────────
    // Liberation "Era of New Wave" activates Twilight Tango. Inside that state,
    // Death Knell and Fatal Finale become available. Imminent Oblivion (Forte
    // heavy) needs full Substance, built primarily by skill/basic usage.
    1107: [
        { skillKey: 'liberation_death_knell',        requires: ['liberation'], gate: 'state',
          note: 'Available inside Twilight Tango (cast Resonance Liberation first).' },
        { skillKey: 'liberation_fatal_finale',       requires: ['liberation', 'liberation_death_knell'], gate: 'state',
          note: 'The finisher of the Twilight Tango sequence (after Liberation / Death Knell).' },
        { skillKey: 'skill_chromatic_splendor',      requires: ['skill'], gate: 'state',
          note: 'Follow-up to Resonance Skill — cast Art of Violence first.' },
        { skillKey: 'forte_heavy_imminent_oblivion', requires: ['skill', 'skill_chromatic_splendor', 'basic_necessary_measures_3'], gate: 'resource',
          note: 'Consumes full Substance — build it with Skill / Necessary Measures before casting.' },
        { skillKey: 'basic_necessary_measures_1',    requires: ['skill', 'skill_chromatic_splendor'], gate: 'resource',
          note: 'Replaces Basic Attack while Moldable Crystals are held (generated by Resonance Skill).' },
    ],

    // ── Hiyuki (1108) ────────────────────────────────────────────────────────
    // Two stances: Present Self (default) and Foreclaimed Self (entered via
    // Liberation). The Fore basics/heavies only exist in Foreclaimed Self.
    // Iai (Forte basic) consumes Snowforged stacks.
    1108: [
        { skillKey: 'basic_fore_1', requires: ['liberation_inward_vision', 'liberation_blade_liberation'], gate: 'form',
          note: 'Foreclaimed Self stance — entered via Resonance Liberation.' },
        { skillKey: 'heavy_fore',   requires: ['liberation_inward_vision', 'liberation_blade_liberation'], gate: 'form',
          note: 'Foreclaimed Self stance — entered via Resonance Liberation.' },
        { skillKey: 'heavy_bitterfrost_fore', requires: ['liberation_inward_vision', 'liberation_blade_liberation'], gate: 'form',
          note: 'Foreclaimed Self stance — entered via Resonance Liberation.' },
        { skillKey: 'forte_basic_iai', requires: ['skill_present', 'skill_jade_cleave', 'skill_petalfall'], gate: 'resource',
          note: 'Consumes Snowforged stacks — build them with Resonance Skill first.' },
    ],

    // ── Jinhsi (1304) ────────────────────────────────────────────────────────
    // Incarnation state (entered via Forte/Liberation) unlocks the Incarnation
    // basic and heavy chains plus the Illuminous Epiphany finishers.
    1304: [
        { skillKey: 'forte_basic_incarnation_basic_attack_1', requires: ['liberation', 'skill_overflowing_radiance'], gate: 'form',
          note: 'Incarnation state — entered via Resonance Skill / Liberation.' },
        { skillKey: 'forte_heavy_incarnation_heavy_attack',   requires: ['liberation', 'skill_overflowing_radiance'], gate: 'form',
          note: 'Incarnation state — entered via Resonance Skill / Liberation.' },
        { skillKey: 'forte_heavy_crescent_divinity',          requires: ['forte_basic_incarnation_basic_attack_4', 'liberation'], gate: 'form',
          note: 'Incarnation finisher — chains from the Incarnation basic sequence.' },
        { skillKey: 'forte_heavy_illuminous_epiphany_solar_flare',  requires: ['liberation'], gate: 'state',
          note: 'Empowered by Resonance Liberation (Purge of Light).' },
        { skillKey: 'forte_heavy_illuminous_epiphany_stella_glamor', requires: ['liberation'], gate: 'state',
          note: 'Empowered by Resonance Liberation (Purge of Light).' },
        { skillKey: 'skill_overflowing_radiance', requires: ['skill'], gate: 'state',
          note: 'Follow-up to Resonance Skill (Trailing Lights of Eons).' },
    ],

    // ── Changli (1205) ───────────────────────────────────────────────────────
    // True Sight has Capture → Conquest → Charge progression; Flaming Sacrifice
    // (Forte heavy) consumes all stacks built during the rotation.
    1205: [
        { skillKey: 'skill_true_sight_conquest', requires: ['skill_true_sight_capture'], gate: 'state',
          note: 'Second stage of True Sight — cast Capture first.' },
        { skillKey: 'skill_true_sight_charge',   requires: ['skill_true_sight_capture', 'skill_true_sight_conquest'], gate: 'state',
          note: 'Third stage of True Sight.' },
        { skillKey: 'forte_heavy_flaming_sacrifice', requires: ['liberation', 'skill_true_sight_capture'], gate: 'resource',
          note: 'Consumes accumulated stacks — build them before casting.' },
    ],

    // ── Cantarella (1607) ──────────────────────────────────────────────────────
    // Forte "Between Illusion and Reality" enters Mirage. In Mirage the basic
    // chain becomes Phantom Sting and the Resonance Skill becomes Flickering
    // Reverie. The Phantom Sting stages are sequential.
    1607: [
        { skillKey: 'skill_flickering_reverie', requires: ['skill_jolt', 'liberation_flowing_suffocation', 'forte_heavy_phantom_sting_1'], gate: 'form',
          note: 'Resonance Skill becomes Flickering Reverie while in Mirage.' },
        { skillKey: 'forte_heavy_phantom_sting_2', requires: ['forte_heavy_phantom_sting_1'], gate: 'form',
          note: 'Second stage of the Phantom Sting chain (Mirage).' },
        { skillKey: 'forte_heavy_phantom_sting_3', requires: ['forte_heavy_phantom_sting_2'], gate: 'form',
          note: 'Third stage of the Phantom Sting chain (Mirage).' },
        { skillKey: 'liberation_diffusion', requires: ['liberation_flowing_suffocation'], gate: 'state',
          note: 'Follow-up to the Resonance Liberation.' },
    ],

    // ── Phoebe (1506) ──────────────────────────────────────────────────────────
    // Forte "Radiant Invocation" consumes full Prayer to cast Absolution Litany
    // / Utter Confession. The Chamuel's Star sequence chains from the skill.
    1506: [
        { skillKey: 'forte_heavy_absolution_litany',   requires: ['skill', 'liberation', 'skill_chamuel_s_star_1'], gate: 'resource',
          note: 'Consumes full Prayer — build it with Skill / Liberation first.' },
        { skillKey: 'forte_heavy_utter_confession',    requires: ['skill', 'liberation', 'skill_chamuel_s_star_1'], gate: 'resource',
          note: 'Consumes full Prayer — build it with Skill / Liberation first.' },
        { skillKey: 'skill_chamuel_s_star_2', requires: ['skill_chamuel_s_star_1'], gate: 'state',
          note: 'Second stage of Chamuel\u2019s Star.' },
        { skillKey: 'skill_chamuel_s_star_3', requires: ['skill_chamuel_s_star_1', 'skill_chamuel_s_star_2'], gate: 'state',
          note: 'Third stage of Chamuel\u2019s Star.' },
    ],
});

// =============================================================================
// Lookups
// =============================================================================

/**
 * Get the rules for a resonator, or an empty array if none are defined.
 * @param {number|string} resonatorId
 * @returns {Array<object>}
 */
export function rulesForResonator(resonatorId) {
    return ROTATION_RULES[Number(resonatorId)] ?? [];
}

/**
 * Whether any gating rules exist for a resonator.
 * @param {number|string} resonatorId
 * @returns {boolean}
 */
export function hasRules(resonatorId) {
    return (ROTATION_RULES[Number(resonatorId)]?.length ?? 0) > 0;
}

// =============================================================================
// State definitions, keyed by resonator id.
// =============================================================================
//
// A state is a mode the character is in for part of the rotation, entered by a
// skill and exited by duration / a consuming skill / end of rotation. The
// rotation-state model uses these to compute which states are active at each
// step, which in turn resolves `inState` chain/inherent effects and (later)
// state-gated off-field and Tune Break interactions.
//
// StateDef shape:
//   { name, enter: { keys?, types? }, exit: { mode, keys?, types?, steps? } }
//
// exit.mode:
//   'persist'    — active until the rotation ends (most on-field forms)
//   'consumedBy' — ends when a listed key/type is cast
//   'duration'   — active for `steps` rotation steps (an approximation)

export const STATE_DEFS = Object.freeze({
    // Carlotta — Liberation "Era of New Wave" activates Twilight Tango; it
    // persists through the burst window (ends when she swaps off / it times out,
    // neither of which the single-character sim models → persist).
    1107: [
        { name: 'Twilight Tango',
          enter: { keys: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Hiyuki — Liberation enters Foreclaimed Self (her empowered stance), which
    // replaces Present Self. Treated as persisting for the rest of the rotation.
    1108: [
        { name: 'Foreclaimed Self',
          enter: { keys: ['liberation_inward_vision', 'liberation_blade_liberation'] },
          exit:  { mode: 'persist' } },
        { name: 'Present Self',
          // Default stance — active from the start; ends once Foreclaimed Self begins.
          initiallyActive: true,
          enter: { keys: [], types: [] },
          exit:  { mode: 'consumedBy', keys: ['liberation_inward_vision', 'liberation_blade_liberation'] } },
    ],

    // Jinhsi — Incarnation state is entered via Liberation / the empowered skill
    // and powers the Incarnation basic/heavy chains.
    1304: [
        { name: 'Incarnation',
          enter: { keys: ['liberation', 'skill_overflowing_radiance'] },
          exit:  { mode: 'persist' } },
    ],

    // Aemeath — Resonance Mode - Tune Rupture (her Tune Break mode). Entered via
    // Forte; persists through the rupture window.
    1210: [
        { name: 'Resonance Mode - Tune Rupture',
          enter: { types: ['forte_basic', 'forte_heavy'] },
          exit:  { mode: 'persist' } },
    ],

    // Denia — Entropy Shift states (her Tune Strain mode), entered via Forte.
    1211: [
        { name: 'Entropy Shift',
          enter: { types: ['forte_basic', 'forte_heavy'] },
          exit:  { mode: 'persist' } },
    ],

    // Phrolova — Liberation "Waltz of Forsaken Depths" enters Maestro state (24s).
    // All liberation-type keys in the autoSkillMap are cast WITHIN Maestro; the
    // first liberation cast marks Maestro's activation.
    1608: [
        { name: 'Maestro',
          enter: { types: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Ciaccona — Liberation "Singer's Triple Cadenza" enters Recital.
    // Recital persists until she switches back on-field (modelled as persist).
    1407: [
        { name: 'Recital',
          enter: { keys: ['liberation_improvised_symphonic_poem_skill'] },
          exit:  { mode: 'persist' } },
    ],
});

/**
 * State definitions for a resonator, or an empty array if none.
 * @param {number|string} resonatorId
 * @returns {Array<object>}
 */
export function stateDefsForResonator(resonatorId) {
    return STATE_DEFS[Number(resonatorId)] ?? [];
}
