/**
 * Rotation prerequisite rules — mechanics-aware gating for the rotation builder.
 *
 * Phase 10 introduces a per-character rule table describing which rotation
 * steps are *gated* behind other steps. In Wuthering Waves many skills are
 * only available after a precondition is met:
 *
 *   - State-gated: a skill is only usable "while in <state>", and that state
 *     is entered by casting some other skill (e.g. Carlotta's Fatal Finale is
 *     only available inside Twilight Tango, entered by her Liberation).
 *   - Resource-gated: a skill consumes a Forte gauge that must be built up
 *     first (e.g. Carlotta's Imminent Oblivion needs full Substance).
 *   - Form/stance-gated: an alternate basic-attack chain that only exists in a
 *     special mode (e.g. Hiyuki's Foreclaimed Self basics, Jinhsi's
 *     Incarnation basics).
 *
 * Design principles
 * -----------------
 * 1. NON-BLOCKING. These rules drive *warnings*, never hard prevention. WuWa
 *    rotations are intricate and players know their character better than a
 *    heuristic. The validator informs; the user decides.
 * 2. CURATED, not auto-parsed. The descriptions are too varied to parse
 *    reliably into correct dependency directions. This table is hand-authored
 *    from the clearest, highest-impact gates, and is designed to grow
 *    incrementally — adding a character is a localized, low-risk edit.
 * 3. DATA-REFERENCED. Rules reference real autoSkillMap keys (verified against
 *    the dataset) so a key rename surfaces immediately in the validator tests.
 *
 * Rule shape
 * ----------
 *   {
 *     skillKey:  string        — the gated step (autoSkillMap key)
 *     requires:  string[]      — keys that satisfy the gate; ANY one earlier in
 *                                the rotation satisfies it (logical OR)
 *     gate:      'state'|'resource'|'form'  — category, for the warning copy
 *     note:      string        — short human explanation shown in the warning
 *   }
 *
 * A rule is "satisfied" for a given rotation position if at least one of its
 * `requires` keys appears at an earlier index. If none do, the validator emits
 * a warning for that step.
 */

// =============================================================================
// Per-resonator rule table, keyed by resonator id.
// =============================================================================
//
// Only characters with clear, impactful gates are listed. Absence of a
// character means "no gating rules" — every step is always considered valid.

export const ROTATION_RULES = Object.freeze({
    // ── Carlotta (1107) ──────────────────────────────────────────────────────
    // Liberation "Era of New Wave" activates Twilight Tango. Inside that state,
    // Death Knell and Fatal Finale become available. Imminent Oblivion (Forte
    // heavy) needs full Substance, built primarily by skill/basic usage.
    1107: [
        { skillKey: 'liberation_death_knell',        requires: ['liberation'], gate: 'state',
          note: 'Available inside Twilight Tango (cast Resonance Liberation first).' },
        { skillKey: 'liberation_fatal_finale',       requires: ['liberation', 'liberation_death_knell'], gate: 'state',
          note: 'The finisher of the Twilight Tango sequence (after Liberation / Death Knell).' },
        { skillKey: 'skill_chromatic_splendor',      requires: ['skill'], gate: 'state',
          note: 'Follow-up to Resonance Skill — cast Art of Violence first.' },
        { skillKey: 'forte_heavy_imminent_oblivion', requires: ['skill', 'skill_chromatic_splendor', 'basic_necessary_measures_3'], gate: 'resource',
          note: 'Consumes full Substance — build it with Skill / Necessary Measures before casting.' },
        { skillKey: 'basic_necessary_measures_1',    requires: ['skill', 'skill_chromatic_splendor'], gate: 'resource',
          note: 'Replaces Basic Attack while Moldable Crystals are held (generated by Resonance Skill).' },
    ],

    // ── Hiyuki (1108) ────────────────────────────────────────────────────────
    // Two stances: Present Self (default) and Foreclaimed Self (entered via
    // Liberation). The Fore basics/heavies only exist in Foreclaimed Self.
    // Iai (Forte basic) consumes Snowforged stacks.
    1108: [
        { skillKey: 'basic_fore_1', requires: ['liberation_inward_vision', 'liberation_blade_liberation'], gate: 'form',
          note: 'Foreclaimed Self stance — entered via Resonance Liberation.' },
        { skillKey: 'heavy_fore',   requires: ['liberation_inward_vision', 'liberation_blade_liberation'], gate: 'form',
          note: 'Foreclaimed Self stance — entered via Resonance Liberation.' },
        { skillKey: 'heavy_bitterfrost_fore', requires: ['liberation_inward_vision', 'liberation_blade_liberation'], gate: 'form',
          note: 'Foreclaimed Self stance — entered via Resonance Liberation.' },
        { skillKey: 'forte_basic_iai', requires: ['skill_present', 'skill_jade_cleave', 'skill_petalfall'], gate: 'resource',
          note: 'Consumes Snowforged stacks — build them with Resonance Skill first.' },
    ],

    // ── Jinhsi (1304) ────────────────────────────────────────────────────────
    // Incarnation state (entered via Forte/Liberation) unlocks the Incarnation
    // basic and heavy chains plus the Illuminous Epiphany finishers.
    1304: [
        { skillKey: 'forte_basic_incarnation_basic_attack_1', requires: ['liberation', 'skill_overflowing_radiance'], gate: 'form',
          note: 'Incarnation state — entered via Resonance Skill / Liberation.' },
        { skillKey: 'forte_heavy_incarnation_heavy_attack',   requires: ['liberation', 'skill_overflowing_radiance'], gate: 'form',
          note: 'Incarnation state — entered via Resonance Skill / Liberation.' },
        { skillKey: 'forte_heavy_crescent_divinity',          requires: ['forte_basic_incarnation_basic_attack_4', 'liberation'], gate: 'form',
          note: 'Incarnation finisher — chains from the Incarnation basic sequence.' },
        { skillKey: 'forte_heavy_illuminous_epiphany_solar_flare',  requires: ['liberation'], gate: 'state',
          note: 'Empowered by Resonance Liberation (Purge of Light).' },
        { skillKey: 'forte_heavy_illuminous_epiphany_stella_glamor', requires: ['liberation'], gate: 'state',
          note: 'Empowered by Resonance Liberation (Purge of Light).' },
        { skillKey: 'skill_overflowing_radiance', requires: ['skill'], gate: 'state',
          note: 'Follow-up to Resonance Skill (Trailing Lights of Eons).' },
    ],

    // ── Changli (1205) ───────────────────────────────────────────────────────
    // True Sight has Capture → Conquest → Charge progression; Flaming Sacrifice
    // (Forte heavy) consumes all stacks built during the rotation.
    1205: [
        { skillKey: 'skill_true_sight_conquest', requires: ['skill_true_sight_capture'], gate: 'state',
          note: 'Second stage of True Sight — cast Capture first.' },
        { skillKey: 'skill_true_sight_charge',   requires: ['skill_true_sight_capture', 'skill_true_sight_conquest'], gate: 'state',
          note: 'Third stage of True Sight.' },
        { skillKey: 'forte_heavy_flaming_sacrifice', requires: ['liberation', 'skill_true_sight_capture'], gate: 'resource',
          note: 'Consumes accumulated stacks — build them before casting.' },
    ],

    // ── Cantarella (1607) ──────────────────────────────────────────────────────
    // Forte "Between Illusion and Reality" enters Mirage. In Mirage the basic
    // chain becomes Phantom Sting and the Resonance Skill becomes Flickering
    // Reverie. The Phantom Sting stages are sequential.
    1607: [
        { skillKey: 'skill_flickering_reverie', requires: ['skill_jolt', 'liberation_flowing_suffocation', 'forte_heavy_phantom_sting_1'], gate: 'form',
          note: 'Resonance Skill becomes Flickering Reverie while in Mirage.' },
        // Mirage's own text: "[Normal Attack] right after casting the skill
        // [that entered Mirage] to cast Basic Attack [Phantom Sting Stage 2]"
        // — so the Mirage-entering casts (Delusive Dive / S3 Liberation) grant
        // Stage 2 directly, alongside the normal Stage 1 chain.
        { skillKey: 'forte_heavy_phantom_sting_2', requires: ['forte_heavy_phantom_sting_1', 'basic_delusive_dive', 'liberation_flowing_suffocation'], gate: 'form',
          note: 'Second stage of the Phantom Sting chain — chains from Stage 1 or directly after entering Mirage (Delusive Dive / Flowing Suffocation).' },
        { skillKey: 'forte_heavy_phantom_sting_3', requires: ['forte_heavy_phantom_sting_2'], gate: 'form',
          note: 'Third stage of the Phantom Sting chain (Mirage).' },
        { skillKey: 'liberation_diffusion', requires: ['liberation_flowing_suffocation'], gate: 'state',
          note: 'Follow-up to the Resonance Liberation.' },
    ],

    // ── Phoebe (1506) ──────────────────────────────────────────────────────────
    // Forte "Radiant Invocation" consumes full Prayer to cast Absolution Litany
    // / Utter Confession. The Chamuel's Star sequence chains from the skill.
    1506: [
        { skillKey: 'forte_heavy_absolution_litany',   requires: ['skill', 'liberation', 'skill_chamuel_s_star_1'], gate: 'resource',
          note: 'Consumes full Prayer — build it with Skill / Liberation first.' },
        { skillKey: 'forte_heavy_utter_confession',    requires: ['skill', 'liberation', 'skill_chamuel_s_star_1'], gate: 'resource',
          note: 'Consumes full Prayer — build it with Skill / Liberation first.' },
        { skillKey: 'skill_chamuel_s_star_2', requires: ['skill_chamuel_s_star_1'], gate: 'state',
          note: 'Second stage of Chamuel\u2019s Star.' },
        { skillKey: 'skill_chamuel_s_star_3', requires: ['skill_chamuel_s_star_1', 'skill_chamuel_s_star_2'], gate: 'state',
          note: 'Third stage of Chamuel\u2019s Star.' },
    ],
});

// =============================================================================
// Lookups
// =============================================================================

/**
 * Get the rules for a resonator, or an empty array if none are defined.
 * @param {number|string} resonatorId
 * @returns {Array<object>}
 */
export function rulesForResonator(resonatorId) {
    return ROTATION_RULES[Number(resonatorId)] ?? [];
}

/**
 * Whether any gating rules exist for a resonator.
 * @param {number|string} resonatorId
 * @returns {boolean}
 */
export function hasRules(resonatorId) {
    return (ROTATION_RULES[Number(resonatorId)]?.length ?? 0) > 0;
}

// =============================================================================
// State definitions, keyed by resonator id.
// =============================================================================
//
// A state is a mode the character is in for part of the rotation, entered by a
// skill and exited by duration / a consuming skill / end of rotation. The
// rotation-state model uses these to compute which states are active at each
// step, which in turn resolves `inState` chain/inherent effects and (later)
// state-gated off-field and Tune Break interactions.
//
// StateDef shape:
//   { name, enter: { keys?, types? }, exit: { mode, keys?, types?, steps? } }
//
// exit.mode:
//   'persist'    — active until the rotation ends (most on-field forms)
//   'consumedBy' — ends when a listed key/type is cast
//   'duration'   — active for `steps` rotation steps (an approximation)

export const STATE_DEFS = Object.freeze({
    // Carlotta — Liberation "Era of New Wave" activates Twilight Tango; it
    // persists through the burst window (ends when she swaps off / it times out,
    // neither of which the single-character sim models → persist).
    1107: [
        { name: 'Twilight Tango',
          enter: { keys: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Brant — Intro "Applaud for Me!" grants [Interlude Applause]: "The next
    // Mid-air Attack begins at [Stage 2]. This effect ends when Brant lands
    // early or is switched out." One-shot license consumed by the first
    // mid-air attack (landing-early isn't modeled).
    1206: [
        { name: 'Interlude Applause',
          enter: { keys: ['intro'] },
          exit:  { mode: 'consumedBy', types: ['midair'] } },
    ],

    // Hiyuki — Liberation enters Foreclaimed Self (her empowered stance), which
    // replaces Present Self. Treated as persisting for the rest of the rotation.
    1108: [
        { name: 'Foreclaimed Self',
          enter: { keys: ['liberation_inward_vision', 'liberation_blade_liberation'] },
          exit:  { mode: 'persist' } },
        { name: 'Present Self',
          // Default stance — active from the start; ends once Foreclaimed Self begins.
          initiallyActive: true,
          enter: { keys: [], types: [] },
          exit:  { mode: 'consumedBy', keys: ['liberation_inward_vision', 'liberation_blade_liberation'] } },
    ],

    // Jinhsi — Incarnation state is entered via Liberation / the empowered skill
    // and powers the Incarnation basic/heavy chains.
    1304: [
        { name: 'Incarnation',
          enter: { keys: ['liberation', 'skill_overflowing_radiance'] },
          exit:  { mode: 'persist' } },
    ],

    // Aemeath — Stardust Resonance ONLY.
    //
    // A "Resonance Mode - Tune Rupture" state used to sit here, entered by any
    // forte_basic/forte_heavy cast. It was wrong twice over: a Resonance Mode is
    // a BUILD-LEVEL toggle (build.resonanceMode → effect.mode → modeGateOk), not
    // something a cast enters, and it is locked for the whole fight — so the
    // state lit up mid-rotation, and lit up in Fusion Burst mode too, because
    // the name was hardcoded to the other mode. Modes have their own gate; a
    // second path for the same concept could only ever disagree with the first.
    1210: [
        // "Casting this skill grants … Enter [Stardust Resonance] for 30s."
        // "## Stardust Resonance — Enhance the effect of Resonance Skill
        //  [Seraphic Duet]. This effect ends after [Seraphic Duet] is cast 2
        //  times." BOTH ends are stated, so both are modelled: the 30s timer or
        //  a budget of two Seraphic Duet casts, whichever runs out first. It
        //  selects her STRONGER Fusion Burst multiplier table
        //  (enemy-status.js AFFLICTION_TRIGGERS, whose `casts` matches `uses`).
        { name: 'Stardust Resonance',
          enter: { keys: ['liberation_heavenfall_edict_overdrive'] },
          exit:  { mode: 'secondsOrConsumedBy', seconds: 30, uses: 2,
                   keys: ['forte_heavy_seraphic_duet_encore', 'forte_heavy_seraphic_duet_overture'] } },
        // "[Heavenfall Edict - Overdrive] … Enter [Heavenfall Edict: Unbound]
        //  for 60s." / "When in [Heavenfall Edict - Unbound] and [Resonance
        //  Rate] reaches the limit, enter [Instant Response]." / "Casting
        //  [Heavy Attack - Aemeath: Charged II], [Heavy Attack - Mech: Charged
        //  II], or Resonance Liberation [Heavenfall Edict: Finale] ends
        //  [Instant Response]."
        //
        // Entered on the Overdrive cast, exactly as Stardust Resonance is: the
        // Resonance Rate limit is a resource the rotation is authored to reach,
        // and the state is nested inside Unbound's own 60s anyway. Both stated
        // ends are modelled — the 60s Unbound timer, or the first of the three
        // consuming casts.
        //
        // Three effects were resolving OFF for want of it, all of them large:
        // S1's +300% Crit. DMG and the inherent's +200% DMG Amplification on her
        // two Heavy Attacks, and S3's Fusion Burst infliction on the same casts
        // (enemy-status.js STATUS_APPLY_RULES).
        { name: 'Instant Response',
          enter: { keys: ['liberation_heavenfall_edict_overdrive'] },
          exit:  { mode: 'secondsOrConsumedBy', seconds: 60, uses: 1,
                   keys: ['heavy_aemeath_charged_ii', 'heavy_mech_charged_ii',
                          'liberation_heavenfall_edict_finale'] } },
    ],

    // Liberation/Forte STANCES whose kits state no timer (2026-08-01). Each is
    // entered by one cast and, per the project's standing reading of silence,
    // holds until something cancels it — which for a single rotation means
    // persist. Every one of these gates a chain effect that was resolving OFF
    // because the parser had no state to bind it to.
    //
    // Lingyang — Liberation "Strive: Lion's Vigor" grants [Lion's Vigor]
    // ("Lingyang gains 50% Glacio DMG Bonus"), with no stated duration.
    1104: [
        { name: "Lion's Vigor",
          enter: { keys: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Rover: Electro — "clear all [Electric Surge] to enter [Apex Resonance]",
    // from the HOLD form of Resonance Skill [Overshock]. Apex Resonance is what
    // unlocks his [Thrum of All Sounds] chain, so any Thrum key also proves he
    // is in it — which is why they count as entering keys too. His S5 ("Crit.
    // DMG is increased by 20% while in Apex Resonance") was the one state-gated
    // effect the tracker could not resolve before 2026-08-01.
    1309: [
        { name: 'Apex Resonance',
          enter: { keys: [
              'forte_heavy_overshock',
              'forte_heavy_thrum_of_all_sounds_spectro_1',
              'forte_heavy_thrum_of_all_sounds_havoc_1',
              'forte_heavy_thrum_of_all_sounds_aero',
              'forte_heavy_thrum_of_all_sounds_silencing_blade',
          ] },
          exit:  { mode: 'persist' } },
    ],

    // Mortefi — Liberation "Violent Finale" applies [Burning Rhapsody] to the
    // whole team (the Marcato coordinated-attack window). No stated duration.
    1204: [
        { name: 'Burning Rhapsody',
          enter: { keys: ['liberation_violent_finale_damage'] },
          exit:  { mode: 'persist' } },
    ],

    // Calcharo — Liberation enters [Deathblade Gear], which replaces his Basic
    // Attack and reclassifies Heavy/Dodge Counter as Liberation DMG. The kit
    // states the state ENDS (his next Intro is replaced afterwards) but never
    // says when, so persist.
    1301: [
        { name: 'Deathblade Gear',
          enter: { keys: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Camellya — "[Camellya] enters [Budding Mode] after casting [Ephemeral]."
    1603: [
        { name: 'Budding Mode',
          enter: { keys: ['forte_heavy_ephemeral'] },
          exit:  { mode: 'persist' } },
    ],

    // Denia — two stances + the mutually-exclusive timed Entropy Shift pair,
    // all straight from her Liberation text (2026-07-05): she starts in
    // [Stagecraft Form] (her Intro "It's Been A While!" is Stagecraft-only and
    // opens the reference rotation). "Final Act - Stagecraft Form: after
    // performing this skill, obtain [Entropy Shift: Breakdown Form] for 12s,
    // then switch to [Breakdown Form]" / "Final Act - Breakdown Form: after
    // casting this skill, obtain [Entropy Shift: Stagecraft Form], which lasts
    // for 30s, and then switch to [Stagecraft Form]". Each Entropy Shift
    // "removes the [other] effect" → secondsOrConsumedBy on the other's enter
    // keys. Intro "Knock Knock" (Breakdown variant) also grants Entropy
    // Shift: Breakdown Form for 12s. The `entropy shift states` alias matches
    // her S6 "While in Entropy Shift states" gate exactly.
    1211: [
        { name: 'Stagecraft Form',
          initiallyActive: true,
          enter: { keys: ['liberation_final_act_breakdown_form'] },
          exit:  { mode: 'consumedBy', keys: ['liberation_final_act_stagecraft_form'] } },
        { name: 'Breakdown Form',
          enter: { keys: ['liberation_final_act_stagecraft_form'] },
          exit:  { mode: 'consumedBy', keys: ['liberation_final_act_breakdown_form'] } },
        { name: 'Entropy Shift: Breakdown Form',
          aliases: ['entropy shift states'],
          enter: { keys: ['liberation_final_act_stagecraft_form', 'intro_knock_knock'] },
          exit:  { mode: 'secondsOrConsumedBy', seconds: 12, keys: ['liberation_final_act_breakdown_form'] } },
        { name: 'Entropy Shift: Stagecraft Form',
          aliases: ['entropy shift states'],
          enter: { keys: ['liberation_final_act_breakdown_form'] },
          exit:  { mode: 'secondsOrConsumedBy', seconds: 30, keys: ['liberation_final_act_stagecraft_form', 'intro_knock_knock'] } },
    ],

    // Phrolova — Liberation "Waltz of Forsaken Depths" enters Maestro state (24s).
    // All liberation-type keys in the autoSkillMap are cast WITHIN Maestro; the
    // first liberation cast marks Maestro's activation.
    1608: [
        { name: 'Maestro',
          enter: { types: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Ciaccona — Liberation "Singer's Triple Cadenza" enters Recital.
    // Recital persists until she switches back on-field (modelled as persist).
    1407: [
        { name: 'Recital',
          enter: { keys: ['liberation_improvised_symphonic_poem_skill'] },
          exit:  { mode: 'persist' } },
    ],

    // Phoebe — Absolution / Confession, entered via the Forte heavy attacks that
    // consume full Prayer. Per her own kit text ("Absolution and Confession
    // cannot coexist. Entering into one will end the other" / "When Divine
    // Voice is exhausted, Phoebe will not exit the Absolution or Confession
    // status") — mutually exclusive, each ended only by the other being
    // entered (Divine Voice itself isn't modeled, so re-entry gating is
    // skipped; the consumedBy relationship is what matters for the timeline).
    // Neither is active at rotation start (she begins in neither status).
    1506: [
        { name: 'Absolution',
          enter: { keys: ['forte_heavy_absolution_litany'] },
          exit:  { mode: 'consumedBy', keys: ['forte_heavy_utter_confession'] } },
        { name: 'Confession',
          enter: { keys: ['forte_heavy_utter_confession'] },
          exit:  { mode: 'consumedBy', keys: ['forte_heavy_absolution_litany'] } },
    ],

    // Cantarella — Mirage, entered via Heavy Attack Delusive Dive (base kit) or
    // Resonance Liberation Flowing Suffocation (S3 enhancement). Per her own
    // kit text: "Mirage lasts for 8s. Mirage ends when Trance is depleted." —
    // a REAL timed expiry (exit.mode 'seconds', not the step-count 'duration'
    // approximation), confirmed by the maintainer 2026-06-27. The Trance-
    // depletion exit isn't modeled (Trance is an unmodeled resource); the timer
    // is the trackable part.
    1607: [
        { name: 'Mirage',
          enter: { keys: ['basic_delusive_dive', 'liberation_flowing_suffocation'] },
          exit:  { mode: 'seconds', seconds: 8 } },
    ],

    // Lucilla — "Clear As Day Buff" (S2.0's Déjà Vu / Resonance-Mode-gated
    // enhancement): entered by casting Liberation "Clear As Day" itself, per
    // her own kit text "continue to exist when in Reminiscence [entered by
    // the same Liberation cast, per 'Clear As Day' deals DMG and enters
    // Reminiscence] and last for 30s after Reminiscence ends [per 'Letting
    // It Go' base kit text: 'Casting Letting It Go ends Reminiscence']." Mode-
    // switching as an additional exit isn't modeled — confirmed safe by the
    // maintainer 2026-06-27: Resonance Mode is locked for the whole sim/team
    // comp, never switches mid-rotation.
    1109: [
        { name: 'Clear As Day Buff',
          enter: { keys: ['liberation'] },
          exit:  { mode: 'consumedByThenSeconds', keys: ['liberation_letting_it_go'], seconds: 30 } },
    ],
});

/**
 * State definitions for a resonator, or an empty array if none.
 * @param {number|string} resonatorId
 * @returns {Array<object>}
 */
export function stateDefsForResonator(resonatorId) {
    return STATE_DEFS[Number(resonatorId)] ?? [];
}

// =============================================================================
// Stage-entry grants, keyed by resonator id (2026-07-05).
// =============================================================================
//
// The generic stage-ordering check (rotation-graph.js) assumes a staged family
// (Basic 1→2→3…) is strictly sequential. Many kits explicitly BREAK that:
// "Normal Attack right after casting this skill to cast [Basic Attack Stage N]".
// Each entry below is verified against the kit text in wuwa-data.json (the
// quoted grant lives in the GRANTING skill's own description).
//
// Grant shape — a stage step is exempt from the N−1 requirement when ANY of:
//   free:     true      — the family is not actually sequential (e.g. charge
//                         levels named "Lv. 1–3") or has hold/direct entry.
//   after:    string[]  — the IMMEDIATELY preceding rotation step is one of
//                         these keys ("right after / shortly after casting").
//   state:    string    — the named state (STATE_DEFS) is active entering the
//                         step (one-shot licenses like Brant's Interlude
//                         Applause, consumed by the granted cast itself).
//   resource: {name, atLeast} — the curated resource (RESOURCE_DEFS) has
//                         reached the threshold at this step.
//   note:     string    — human copy for the grant chip / tooltip.

export const STAGE_GRANTS = Object.freeze({
    // Brant — Intro "Applaud for Me!" grants [Interlude Applause]: "The next
    // Mid-air Attack begins at [Stage 2]." A persistent one-shot license (ends
    // on landing/switch — unmodeled), so it survives intermediate casts.
    1206: {
        midair_mid_air_attack_2: {
            state: 'interlude applause',
            note: 'Intro (Applaud for Me!) grants Interlude Applause — the next Mid-air Attack begins at Stage 2.',
        },
    },

    // Hiyuki — Dodge Counter (Present): "[Normal Attack] within a certain
    // period after casting this skill to perform [Basic Attack - Present Self
    // Stage 3]"; all three Resonance Skills + the Intro: "hold [Normal Attack]
    // within a certain period after casting this skill to perform [Basic
    // Attack - Present Self Stage 3]"; Intro (Foreclaimed): "[Normal Attack]
    // … to cast [Basic Attack - Foreclaimed Self Stage 2]"; Heavy (Fore) →
    // Fore Stage 2; Bitterfrost → "chain into [Basic Attack - Foreclaimed
    // Self Stage 4] instead"; Dodge Counter (Fore) → Fore Stage 3.
    1108: {
        basic_present_3: {
            after: ['basic_dodge_counter_present', 'skill_present', 'skill_jade_cleave', 'skill_petalfall', 'intro'],
            note: 'Dodge Counter / Resonance Skills / Intro chain into Basic - Present Self Stage 3.',
        },
        basic_fore_2: {
            after: ['heavy_fore', 'intro'],
            note: 'Heavy Attack (Foreclaimed) / Intro chain into Basic - Foreclaimed Self Stage 2.',
        },
        basic_fore_3: {
            after: ['basic_dodge_counter_fore'],
            note: 'Dodge Counter (Foreclaimed) chains into Basic - Foreclaimed Self Stage 3.',
        },
        basic_fore_4: {
            after: ['heavy_bitterfrost_fore'],
            note: 'Bitterfrost Heavy chains into Basic - Foreclaimed Self Stage 4.',
        },
    },

    // Lucilla — Mid-air Attack / Compensate / Spotlight: "[Normal Attack]
    // shortly after casting this skill to cast [Basic Attack Stage 2]";
    // Mid-air Reminiscence → Tracing Forms Stage 2; Dodge Counter
    // Reminiscence → Tracing Forms Stage 3.
    1109: {
        basic_basic_attack_2: {
            after: ['midair_mid_air_attack', 'skill_compensate', 'skill_spotlight'],
            note: 'Mid-air Attack / Compensate / Spotlight chain into Basic Attack Stage 2.',
        },
        liberation_tracing_forms_2: {
            after: ['midair_reminiscence'],
            note: 'Mid-air Attack - Reminiscence chains into Basic - Tracing Forms Stage 2.',
        },
        liberation_tracing_forms_3: {
            after: ['liberation_dodge_counter_reminiscence'],
            note: 'Dodge Counter - Reminiscence chains into Basic - Tracing Forms Stage 3.',
        },
    },

    // Lupa — "After [Dodge Counter], Basic Attack [Starfall], Resonance Skill
    // [Shewolf's Hunt], or Resonance Skill [Feral Fang], Normal Attack in
    // time to cast [Basic Attack Stage 2]."
    1207: {
        basic_2: {
            after: ['basic_dodge_counter', 'basic_starfall', 'skill_skill_damage', 'skill_feral_fang'],
            note: 'Dodge Counter / Starfall / Shewolf’s Hunt / Feral Fang chain into Basic Attack Stage 2.',
        },
    },

    // Galbrena — Intro: "Normal Attack right after casting this skill to
    // perform [Basic Attack Stage 2]"; Basic 4 loops: "Normal Attack right
    // after performing [Basic Attack Stage 4] to perform [Basic Attack Stage
    // 2]"; Liberation: "Normal Attack after casting Resonance Liberation to
    // cast [Basic Attack Stage 2]. While in [Demon Hypostasis], cast [Basic
    // Attack - Seraphic Execution Stage 2] instead."; Volley of Death 1 →
    // Basic 2 / Volley 2-3 → Basic 3; Plunging Attack → Basic 3; Dodge
    // Counter (Blood for Blood) → Basic 4; Intro also holds into Volley
    // Stage 2 / Flamewing Verdict Stage 2 (Demon Hypostasis); Seraphic 5
    // loops to 3; Flamewing Verdict 1 → Seraphic 2, 2-3 → Seraphic 3.
    1208: {
        basic_basic_attack_2: {
            after: ['intro_intro_skill_hellflare_overload', 'basic_basic_attack_4', 'liberation_hellfire_absolution', 'heavy_volley_of_death_1'],
            note: 'Intro / Basic 4 loop / Liberation / Volley of Death Stage 1 chain into Basic Attack Stage 2.',
        },
        basic_basic_attack_3: {
            after: ['heavy_volley_of_death_2', 'heavy_volley_of_death_3', 'midair_ashfall_barrage_plunging_attack'],
            note: 'Volley of Death Stage 2/3 / Plunging Attack chain into Basic Attack Stage 3.',
        },
        basic_basic_attack_4: {
            after: ['basic_dodge_counter_blood_for_blood'],
            note: 'Dodge Counter (Blood for Blood) chains into Basic Attack Stage 4.',
        },
        heavy_volley_of_death_2: {
            after: ['intro_intro_skill_hellflare_overload'],
            note: 'Hold Normal Attack after the Intro casts Volley of Death Stage 2.',
        },
        forte_basic_seraphic_execution_2: {
            after: ['liberation_hellfire_absolution', 'intro_intro_skill_hellflare_overload', 'forte_heavy_flamewing_verdict_1'],
            note: 'Liberation / Intro / Flamewing Verdict Stage 1 chain into Seraphic Execution Stage 2 (Demon Hypostasis).',
        },
        forte_basic_seraphic_execution_3: {
            after: ['forte_basic_seraphic_execution_5', 'forte_heavy_flamewing_verdict_2', 'forte_heavy_flamewing_verdict_3'],
            note: 'Seraphic Execution loops 5 → 3; Flamewing Verdict Stage 2/3 chain into Seraphic Stage 3.',
        },
        forte_heavy_flamewing_verdict_2: {
            after: ['intro_intro_skill_hellflare_overload'],
            note: 'Hold Normal Attack after the Intro (in Demon Hypostasis) casts Flamewing Verdict Stage 2.',
        },
    },

    // Mornye — Dodge Counter → Basic 2; Mid-air Attack → Basic 3; Dodge
    // Counter (Wide Field Observation Mode) → WFO Basic Stage 3.
    1209: {
        basic_basic_attack_2: {
            after: ['basic_dodge_counter'],
            note: 'Dodge Counter chains into Basic Attack Stage 2.',
        },
        basic_basic_attack_3: {
            after: ['midair_mid_air_attack'],
            note: 'Mid-air Attack chains into Basic Attack Stage 3.',
        },
        basic_wide_field_observation_mode_3: {
            after: ['basic_dodge_counter_wide_field_observation_mode'],
            note: 'Dodge Counter (Wide Field Observation Mode) chains into WFO Basic Stage 3.',
        },
    },

    // Aemeath — Intro: "[Resonance Skill] … shortly after casting this skill
    // to cast [Basic Attack - Mech Stage 3] automatically"; Liberation
    // Overdrive: "[Normal Attack] shortly after casting this skill to cast
    // [Basic Attack - Mech Stage 2]"; Seraphic Duet Overture: "Switch into the
    // Mech form … [Normal Attack] within a certain period of time to cast
    // [Basic Attack - Mech Stage 2]"; Seraphic Duet Encore: "Switch back to
    // Aemeath … [Normal Attack] shortly afterward to cast [Basic Attack -
    // Aemeath Stage 2]"; Heavy Charged II → Aemeath Stage 3.
    1210: {
        skill_mech_3: {
            after: ['intro_debut_of_meteoric_radiance'],
            note: 'Intro (Debut of Meteoric Radiance): Form Switch shortly after casts Basic - Mech Stage 3.',
        },
        skill_mech_2: {
            after: ['liberation_heavenfall_edict_overdrive', 'forte_heavy_seraphic_duet_overture'],
            note: 'Liberation Overdrive / Seraphic Duet: Overture chain into Basic - Mech Stage 2.',
        },
        basic_aemeath_2: {
            after: ['forte_heavy_seraphic_duet_encore'],
            note: 'Seraphic Duet: Encore switches back to Aemeath and chains into Basic - Aemeath Stage 2.',
        },
        basic_aemeath_3: {
            after: ['heavy_mech_charged_ii'],
            note: 'Heavy Attack Charged II chains into Basic - Aemeath Stage 3.',
        },
    },

    // Denia — Intro "It's Been A While!": "[Normal Attack] after casting this
    // skill to cast [Basic Attack - Stagecraft Form Stage 4]"; Dodge Counter
    // (Stagecraft): same grant. Dodge Counter (Breakdown): "[Normal Attack]
    // shortly after casting this skill to perform [Basic Attack - Breakdown
    // Form Stage 4] or [Mid-air Attack - Breakdown Form Stage 4]."
    1211: {
        basic_stagecraft_form_4: {
            after: ['intro_it_s_been_a_while', 'basic_dodge_counter_stagecraft_form'],
            note: 'Intro (It’s Been A While!) / Dodge Counter chain directly into Stagecraft Stage 4.',
        },
        basic_breakdown_form_4: {
            after: ['basic_dodge_counter_breakdown_form'],
            note: 'Dodge Counter (Breakdown) chains into Basic - Breakdown Form Stage 4.',
        },
        midair_breakdown_form_4: {
            after: ['basic_dodge_counter_breakdown_form'],
            note: 'Dodge Counter (Breakdown) chains into Mid-air - Breakdown Form Stage 4.',
        },
    },

    // Augusta — Heavy (Steelclash): "[Normal Attack] shortly after performing
    // Heavy Attack to perform [Basic Attack Stage 2]" (incl. the dodge-counter
    // Steelclash variant — same move).
    1306: {
        basic_2: {
            after: ['heavy_heavy_attack_steelclash', 'heavy_dodge_counter_heavy_attack_steelclash'],
            note: 'Heavy Attack (Steelclash) chains into Basic Attack Stage 2.',
        },
    },

    // Yinlin — MAINTAINER-VERIFIED IN-GAME (2026-07-05), not described in any
    // kit text: her Intro chains directly into Basic Attack Stage 4 (Prydwen's
    // community rotation uses it; confirmed correct in-game).
    1302: {
        basic_4: {
            after: ['intro'],
            note: 'Maintainer-verified in-game: Intro chains directly into Basic Attack Stage 4 (undocumented).',
        },
    },

    // Buling — Skill: "Right after casting [Resonance Skill], [Normal Attack]
    // to perform [Basic Attack Stage 4]."
    1307: {
        basic_4: {
            after: ['skill_thunder_talisman'],
            note: 'Right after Resonance Skill (Thunder Talisman), Normal Attack performs Basic Attack Stage 4.',
        },
    },

    // Rebecca — Skill "It's Big Boomin' Time!" / Intro "Yo, It's Big Boomin'
    // Time!": "[Normal Attack] shortly after casting this skill to follow up
    // with [Basic Attack - Guts] Stage 2."
    1308: {
        basic_guts_2: {
            after: ['skill_it_s_big_boomin_time', 'intro_yo_it_s_big_boomin_time'],
            note: 'It’s Big Boomin’ Time! (skill or intro) chains into Basic - Guts Stage 2.',
        },
    },

    // Rover: Aero — Heavy: "[Normal Attack] right after casting the skill to
    // perform [Basic Attack Stage 3] directly"; Mid-air: "[Normal Attack]
    // shortly after landing to cast [Basic Attack Stage 4]."
    1406: {
        basic_3: {
            after: ['heavy_heavy_attack'],
            note: 'Heavy Attack chains into Basic Attack Stage 3 directly.',
        },
        basic_4: {
            after: ['midair_mid_air_attack'],
            note: 'Mid-air Attack (after landing) chains into Basic Attack Stage 4.',
        },
    },

    // Ciaccona — Intro: "Follow up with Basic Attack in time to cast Basic
    // Attack Stage 3"; Mid-air 2: "Normal Attack after Mid-air Attack Stage 2
    // to cast Basic Attack Stage 4"; Dodge Counter: "Normal Attack in time to
    // cast Basic Attack Stage 2."
    1407: {
        basic_2: {
            after: ['basic_dodge_counter'],
            note: 'Dodge Counter chains into Basic Attack Stage 2.',
        },
        basic_3: {
            after: ['intro'],
            note: 'Intro (Roaming with the Wind) chains into Basic Attack Stage 3.',
        },
        basic_4: {
            after: ['midair_mid_air_attack_2'],
            note: 'Mid-air Attack Stage 2 chains into Basic Attack Stage 4.',
        },
    },

    // Iuno — Moonbow Dodge Counter: "When in [Lunar Cycle - New Moon], Normal
    // Attack again shortly after performing this skill to cast Moonbow -
    // Basic Attack Stage 3." (The Moonring Dodge Counter grant exists in text
    // but has no skill-map key — see docs/COMBO-ENTRY-CURATION.md.)
    1410: {
        basic_moonbow_basic_attack_3: {
            after: ['basic_moonbow_dodge_counter'],
            note: 'Moonbow Dodge Counter chains into Moonbow Basic Attack Stage 3.',
        },
    },

    // Cartethyia — Intro: "[Normal Attack] shortly after … to perform [Basic
    // Attack - Cartethyia Stage 2]"; Mid-air Fleurdelys Stage 3 has DIRECT
    // hold entry ("While airborne, hold [Normal Attack] to cast [Mid-air
    // Attack - Fleurdelys Stage 3]"); Mid-air 3 / May Tempest chain into
    // Fleurdelys Basic Stage 3.
    1409: {
        basic_2: {
            after: ['intro_sword_to_mark_tide_s_trace'],
            note: 'Intro (Sword to Mark Tide’s Trace) chains into Basic - Cartethyia Stage 2.',
        },
        forte_heavy_mid_air_attack_3: {
            free: true,
            note: 'While airborne, hold Normal Attack casts Mid-air - Fleurdelys Stage 3 directly.',
        },
        forte_basic_basic_attack_3: {
            after: ['forte_heavy_mid_air_attack_3', 'forte_heavy_may_tempest_break_the_tides'],
            note: 'Mid-air Fleurdelys Stage 3 / May Tempest Break the Tides chain into Basic - Fleurdelys Stage 3.',
        },
    },

    // Qiuyuan — Intro: "Within a certain period of time after casting this
    // skill, [Normal Attack] to perform Basic Attack [Thus Spoke the Blade:
    // Inkwash] Stage 3."; Heavy: "[Normal Attack] within a certain period of
    // time after casting this skill to perform … Inkwash Stage 4."
    1411: {
        forte_heavy_thus_spoke_the_blade_inkwash_3: {
            after: ['intro_skill_damage'],
            note: 'Intro chains into Thus Spoke the Blade: Inkwash Stage 3.',
        },
        forte_heavy_thus_spoke_the_blade_inkwash_4: {
            after: ['heavy_heavy_attack'],
            note: 'Heavy Attack chains into Thus Spoke the Blade: Inkwash Stage 4.',
        },
    },

    // Shorekeeper — Skill (Dim Star Butterfly): "Follow up with [Basic
    // Attack] in time to start the Basic Attack cycle from [Stage 2]."
    1505: {
        basic_2: {
            after: ['skill_dim_star_butterfly'],
            note: 'Dim Star Butterfly chains into the Basic cycle starting at Stage 2.',
        },
    },

    // Sigrika — Intro: "[Normal Attack] shortly after casting [Intro Skill] to
    // cast [Basic Attack Stage 2]"; plus the Full Stop cycle rule: "When
    // Sigrika has at least 50 of [Full Stop], her Basic Attack cycle starts
    // from Stage 2." (Full Stop tracked via RESOURCE_DEFS.)
    1412: {
        basic_basic_attack_2: {
            after: ['intro', 'heavy_heavy_attack'],
            resource: { name: 'Full Stop', atLeast: 50 },
            note: 'Intro / Heavy chain into Basic Stage 2; with ≥50 Full Stop her Basic cycle always starts at Stage 2.',
        },
    },

    // Zani — Skill: "[Normal Attack] within a certain time to perform [Basic
    // Attack Stage 3]".
    1507: {
        basic_3: {
            after: ['skill_standard_defense_protocol'],
            note: 'Resonance Skill (Standard Defense Protocol) chains into Basic Attack Stage 3.',
        },
    },

    // Chisa — Intro: "[Normal Attack] shortly after casting this skill to cast
    // [Basic Attack Stage 2]" (non-Chainsaw) / "[Sawring - Blitz Stage 2]"
    // (Chainsaw Mode); Serrated Loop: "[Normal Attack] shortly after casting
    // this skill to cast [Sawring - Blitz Stage 2]".
    1508: {
        basic_2: {
            after: ['intro'],
            note: 'Intro (Reverberance — Return) chains into Basic Attack Stage 2.',
        },
        forte_heavy_sawring_blitz_2: {
            after: ['skill_serrated_loop', 'intro'],
            note: 'Serrated Loop / Intro (in Chainsaw Mode) chain into Sawring - Blitz Stage 2.',
        },
    },

    // Lynae — "Spark Collision Lv. 1–3" are CHARGE LEVELS of one hold attack
    // (Lumiflow ratio picks the level), not combo stages: "Upon releasing
    // Normal Attack or when [Lumiflow] is full, Lynae casts Spark Collision of
    // varying strengths based on the ratio of [Lumiflow]". Lynae-Style
    // Palettes → Basic Stage 2; Additive Color / To a Vivid Tomorrow /
    // Iridescent Splash / Visual Impact → Kaleidoscopic Parade Basic Stage 2.
    1509: {
        basic_spark_collision_lv_2: { free: true, note: 'Spark Collision levels are charge strengths, not combo stages.' },
        basic_spark_collision_lv_3: { free: true, note: 'Spark Collision levels are charge strengths, not combo stages.' },
        basic_basic_attack_2: {
            after: ['skill_lynae_style_palettes'],
            note: 'Lynae-Style Palettes chains into Basic Attack Stage 2.',
        },
        basic_kaleidoscopic_parade_basic_attack_2: {
            after: ['skill_additive_color', 'liberation_to_a_vivid_tomorrow', 'forte_basic_iridescent_splash', 'forte_basic_visual_impact'],
            note: 'Additive Color / To a Vivid Tomorrow / Iridescent Splash / Visual Impact chain into Kaleidoscopic Parade Basic Stage 2.',
        },
    },

    // Luuk Herssen — Dodge Counter: "[Normal Attack] right after casting this
    // skill to cast [Basic Attack Stage 3]." Mid-air stages 2–3 exist only as
    // named Scythe variants (no trailing digit → invisible to the stage
    // parser), so Stage 4's real predecessors are curated here.
    1510: {
        basic_basic_attack_3: {
            after: ['basic_ground_dodge_counter'],
            note: 'Dodge Counter chains into Basic Attack Stage 3.',
        },
        midair_mid_air_attack_4: {
            after: ['midair_mid_air_attack_3_scythe_dissection', 'midair_mid_air_attack_3_scythe_resction'],
            note: 'Mid-air Stage 3 exists as the Scythe Dissection/Resection variants — either chains into Stage 4.',
        },
    },

    // Lucy — Pulse Interference → Basic 2; Heavy 1 → Basic 3; Dodge Counter →
    // Basic 4; Heavy Stage 2 reachable by holding after Basic 3 / Dodge
    // Counter / Pulse Interference ("Hold [Normal Attack] shortly after …
    // lands to cast [Heavy Attack Stage 2]"); the three Threading heavies and
    // Deadlock chain into Thread Shredding Stage 2.
    1511: {
        basic_basic_attack_2: {
            after: ['skill_pulse_interference'],
            note: 'Resonance Skill (Pulse Interference) chains into Basic Attack Stage 2.',
        },
        basic_basic_attack_3: {
            after: ['heavy_heavy_attack_1'],
            note: 'Heavy Attack Stage 1 chains into Basic Attack Stage 3.',
        },
        basic_basic_attack_4: {
            after: ['basic_dodge_counter'],
            note: 'Dodge Counter chains into Basic Attack Stage 4.',
        },
        heavy_heavy_attack_2: {
            after: ['basic_basic_attack_3', 'basic_dodge_counter', 'skill_pulse_interference'],
            note: 'Hold after Basic 3 / Dodge Counter / Pulse Interference casts Heavy Attack Stage 2 directly.',
        },
        basic_thread_shredding_2: {
            after: ['heavy_single_threading', 'heavy_dual_threading', 'heavy_multithreading', 'skill_deadlock'],
            note: 'Single/Dual/Multi-threading heavies and Deadlock chain into Thread Shredding Stage 2.',
        },
    },

    // Danjin — MAINTAINER-VERIFIED IN-GAME (2026-07-05), not described in kit
    // text: her Resonance Skill weaves INTO the Basic chain (the kit only
    // documents the reverse direction, "after Basic Attack 2 … use Resonance
    // Skill"). Right after Carmine Gleam, Normal Attack lands at Stage 2.
    1602: {
        basic_2: {
            after: ['skill_carmine_gleam_damage'],
            note: 'Maintainer-verified in-game: her skill weaves into the Basic chain — Carmine Gleam chains into Basic Attack Stage 2 (undocumented).',
        },
    },

    // Roccia — Intro: "Use [Basic Attack] right after casting this skill to
    // cast [Basic Attack Stage 4]."
    1606: {
        basic_4: {
            after: ['intro'],
            note: 'Intro (Pero, Help) chains directly into Basic Attack Stage 4.',
        },
    },

    // Cantarella — Intro (Ripple): "[Normal Attack] shortly after casting
    // this skill to start the Basic Attack combo from [Basic Attack Stage 3]."
    // (Her Phantom Sting Mirage entry is handled by the ROTATION_RULES entry.)
    1607: {
        basic_3: {
            after: ['intro_ripple'],
            note: 'Intro (Ripple) starts the Basic combo from Stage 3.',
        },
    },

    // Phrolova — both Intros: "[Normal Attack] shortly after casting this
    // skill to cast [Basic Attack Stage 3]"; Dodge Counter → Basic 3; Heavy →
    // Basic 2.
    1608: {
        basic_2: {
            after: ['heavy_heavy_attack'],
            note: 'Heavy Attack chains into Basic Attack Stage 2.',
        },
        basic_3: {
            after: ['intro_suite_of_immortality', 'intro_suite_of_quietus', 'basic_dodge_counter'],
            note: 'Either Intro / Dodge Counter chains into Basic Attack Stage 3.',
        },
    },

    // Suisui — NOT a game mechanic: a data key-naming artifact. The raw kit
    // text names her Stage 2 "Zephyr StanceStage 2" (missing the space present
    // on every other stage, e.g. "Drizzle Stance Stage 2"), so preprocess.mjs's
    // slug lands as `basic_zephyr_stancestage_2` — one word short of matching
    // its `basic_zephyr_stance_{1,3,4}` siblings. The stage-ordering heuristic
    // reads that as an unrelated single-stage family, so Stage 3 warns "Stage 2
    // should come first" even though Stage 2 (the mis-keyed one) was cast right
    // before it. This grant is the family link the key typo breaks, not a
    // Suisui-specific chain rule.
    1110: {
        basic_zephyr_stance_3: {
            after: ['basic_zephyr_stancestage_2'],
            note: 'Basic Attack - Zephyr Stance Stage 2 (mis-keyed as basic_zephyr_stancestage_2) chains into Stage 3.',
        },
    },
});

/** Stage grants for a resonator, or an empty object if none. */
export function stageGrantsForResonator(resonatorId) {
    return STAGE_GRANTS[Number(resonatorId)] ?? {};
}

// =============================================================================
// Swap-in combo entry, keyed by resonator id.
// =============================================================================
//
// MAINTAINER-VERIFIED IN-GAME (2026-07-05), not documented in any kit text or
// community source: when these resonators are swapped in WITHOUT an Intro
// Skill, an automatic Basic Stage 1 fires and the first user-input Basic lands
// at STAGE 3 — i.e. stages 1–2 are effectively pre-seen at rotation start.
// Verified for Yangyang, Verina, Yinlin + spot-checks Roccia, Camellya.
// Explicitly NOT true for Chisa, Aemeath, Denia (they start at Stage 1).
// The auto-Basic-1's damage is NOT modeled as a step (known gap).

export const SWAP_IN_ENTRY = Object.freeze({
    1302: { family: 'basic', preSeen: [1, 2] },   // Yinlin
    1402: { family: 'basic', preSeen: [1, 2] },   // Yangyang
    1503: { family: 'basic', preSeen: [1, 2] },   // Verina
    1603: { family: 'basic', preSeen: [1, 2] },   // Camellya
    1606: { family: 'basic', preSeen: [1, 2] },   // Roccia
});

/** Swap-in entry seeding for a resonator, or null. */
export function swapInEntryForResonator(resonatorId) {
    return SWAP_IN_ENTRY[Number(resonatorId)] ?? null;
}

// =============================================================================
// Curated resource definitions, keyed by resonator id.
// =============================================================================
//
// Minimal per-rotation resource tracking for gates the kit text quantifies
// exactly. Deliberately simple: gains are per-cast constants, spendAll keys
// zero the pool, `cap` clamps. This is validation/gating-grade tracking, not
// full Phase-B gauge simulation (hit-count/off-field income is out of scope).
//
//   { name, channel?, cap, gains: { skillKey: amount }, spendAll: [skillKey] }
//
// `channel` names the game's own SpecialEnergy channel for this gauge (1–5).
// When it is set, `resourceDefsForResonator(id, dataset)` replaces `cap` with
// the game's declared `SpecialEnergy{channel}Max`, so the number in the sim is
// the number the game ships rather than one read out of kit text. The literal
// `cap` below stays as the offline fallback (a caller with no dataset) and is
// asserted equal to the extracted value by tests/rotation-resources.test.mjs,
// so it cannot silently drift.
//
// What still has to be curated, and why: the channel↔name link, and the gains
// a cast does NOT state.
//
// ~~Income is unreadable and stays curated~~ — that held only while the Buff
// table was undumped. `data/gauge-income.json` (tools/extract/
// extract_gauge_income.py) now reads it: a DT_SkillInfo row's SkillBuff /
// SkillStartBuff / SkillEndBuff resolve to db_buff rows whose GameAttributeID is
// an Energy/SpecialEnergy channel, giving the exact per-cast delta for 50
// resonators. Denia's entry below is filled entirely from it.
//
// The boundary that remains is the CAST: income earned on a HIT lives in
// db_PassiveSkill behind ExtraEffect chains and is not modelled here, which is
// why Changli's Enflamement (1 per True Sight hit) is still hand-written while
// Denia's Intro grant is not. Cross-check a curated `gains` against the
// extraction before trusting it; tests/gauge-income.test.mjs pins the ones the
// game states.

export const RESOURCE_DEFS = Object.freeze({
    // Changli — "Changli can hold up to 4 stacks of Enflamement. Changli obtains
    // 1 stack of Enflamement for every Basic Attack: [True Sight - Conquest] on
    // hit. […] for every Basic Attack: [True Sight - Charge] on hit. Changli
    // obtains 4 stacks of Enflamement for every Resonance Liberation [Radiance
    // of Fealty]." Spent by Heavy Attack [Flaming Sacrifice], which "consumes
    // all stacks of Enflamement" (and requires 4 to cast at all).
    // The two True Sight keys live under `skill_` in autoSkillMap even though
    // the kit text calls them Basic Attacks — the same key spelling her already-
    // curated S2.0 effect override uses.
    1205: [{
        name: 'Enflamement',
        channel: 1,       // SpecialEnergy1Max = 4 in the game's own baseproperty table
        cap: 4,
        gains: {
            skill_true_sight_conquest: 1,
            skill_true_sight_charge: 1,
            liberation: 4,
        },
        spendAll: ['forte_heavy_flaming_sacrifice'],
    }],
    // Sigrika — "After casting [Heavy Attack - Schemata of Runes], gain 50 of
    // [Full Stop], up to 100 points." The Runic variants ARE Schemata casts
    // ("this skill gains the effect of [Runic X]"). Forte Circuit "Learn My
    // True Name": "[Hold Resonance Skill] to consume all [Full Stop]".
    // Denia — the first gauge whose income is READ rather than guessed
    // (data/gauge-income.json, 2026-08-12). Every number below is the game's:
    //   cap 3           SpecialEnergy2Max, matching "Denia can hold up to 3
    //                   [Dark Cores]"
    //   +1 per Intro    rows 1211061/1211062 (her two QTE rows, one per form)
    //                   each grant SpecialEnergy2 +1, matching "Denia obtains 1
    //                   upon casting Intro Skill [It's Been A While!] and Intro
    //                   Skill [Knock Knock]"
    // The spender is the kit's, not the table's: no DT_SkillInfo row spends
    // SpecialEnergy2, so "[Banish - Breakdown Form Stage 2] consumes all [Dark
    // Cores]" remains the source for that one line.
    //
    // What the gauge is FOR: "For each [Dark Core] consumed, the DMG Multiplier
    // of the attack is increased by 150%." The game ships that ladder as damage
    // rows too — 12111052110/…120/…130/…140/…150 are exactly 2.5x/4.0x/5.5x/
    // 7.0x/8.5x her 56.34% display row, i.e. base x (1 + 1.5N) — which is the
    // answer key tests/rotation-resources.test.mjs checks the sim against.
    //
    // KNOWN BOUND: S3 states "Denia now holds up to 5 Dark Cores" (hence five
    // variant rows), but a cap is per-resonator here, not per-chain, so an S3+
    // build is held to 3. No reference rotation casts enough Intros to reach
    // even 3, so nothing today is affected; raising it needs a chain-aware cap.
    1211: [{
        name: 'Dark Core',
        channel: 2,       // SpecialEnergy2Max = 3 in the game's own baseproperty table
        cap: 3,
        gains: {
            intro_it_s_been_a_while: 1,
            intro_knock_knock: 1,
        },
        spendAll: ['skill_banish_breakdown_form_2'],
    }],
    1412: [{
        name: 'Full Stop',
        cap: 100,
        gains: {
            forte_heavy_schemata_of_runes: 50,
            forte_heavy_runic_chain_whip: 50,
            forte_heavy_runic_outburst: 50,
            forte_heavy_runic_soliskin: 50,
        },
        spendAll: ['forte_heavy_forte_circuit_learn_my_true_name'],
    }],
});

/**
 * Resource definitions for a resonator, or an empty array.
 *
 * Pass the dataset to resolve each gauge's cap from the game's own
 * `SpecialEnergy{channel}Max` (stamped onto the resonator by preprocess.mjs
 * from the BinData dump) instead of the curated literal. Without it the
 * literal stands — same number today, guarded by a test.
 *
 * @param {number|string} resonatorId
 * @param {object|null} [dataset]
 */
export function resourceDefsForResonator(resonatorId, dataset = null) {
    const defs = RESOURCE_DEFS[Number(resonatorId)] ?? [];
    if (!dataset || defs.length === 0) return defs;
    const caps = dataset.resonators?.find(entry => entry.id === Number(resonatorId))?.specialEnergyCaps;
    if (!caps) return defs;
    return defs.map(def => {
        const gameCap = def.channel != null ? caps[def.channel] : null;
        return gameCap != null ? { ...def, cap: gameCap } : def;
    });
}
