/**
 * Rotation prerequisite rules — mechanics-aware gating for the rotation builder.
 *
 * Phase 10 introduces a per-character rule table describing which rotation
 * steps are *gated* behind other steps. In Wuthering Waves many skills are
 * only available after a precondition is met:
 *
 *   - State-gated: a skill is only usable "while in <state>", and that state
 *     is entered by casting some other skill (e.g. Carlotta's Fatal Finale is
 *     only available inside Twilight Tango, entered by her Liberation).
 *   - Resource-gated: a skill consumes a Forte gauge that must be built up
 *     first (e.g. Carlotta's Imminent Oblivion needs full Substance).
 *   - Form/stance-gated: an alternate basic-attack chain that only exists in a
 *     special mode (e.g. Hiyuki's Foreclaimed Self basics, Jinhsi's
 *     Incarnation basics).
 *
 * Design principles
 * -----------------
 * 1. NON-BLOCKING. These rules drive *warnings*, never hard prevention. WuWa
 *    rotations are intricate and players know their character better than a
 *    heuristic. The validator informs; the user decides.
 * 2. CURATED, not auto-parsed. The descriptions are too varied to parse
 *    reliably into correct dependency directions. This table is hand-authored
 *    from the clearest, highest-impact gates, and is designed to grow
 *    incrementally — adding a character is a localized, low-risk edit.
 * 3. DATA-REFERENCED. Rules reference real autoSkillMap keys (verified against
 *    the dataset) so a key rename surfaces immediately in the validator tests.
 *
 * Rule shape
 * ----------
 *   {
 *     skillKey:  string        — the gated step (autoSkillMap key)
 *     requires:  string[]      — keys that satisfy the gate; ANY one earlier in
 *                                the rotation satisfies it (logical OR)
 *     gate:      'state'|'resource'|'form'  — category, for the warning copy
 *     note:      string        — short human explanation shown in the warning
 *   }
 *
 * A rule is "satisfied" for a given rotation position if at least one of its
 * `requires` keys appears at an earlier index. If none do, the validator emits
 * a warning for that step.
 */

// `stateActive` only — the same fuzzy name match every state gate in the engine
// uses, so a `whenState` timing rule and an `inState` effect gate can never
// disagree about whether a state is on. rotation-state.js imports nothing, so
// this direction cannot cycle.
import { stateActive } from './rotation-state.js';

// =============================================================================
// Per-resonator rule table, keyed by resonator id.
// =============================================================================
//
// Only characters with clear, impactful gates are listed. Absence of a
// character means "no gating rules" — every step is always considered valid.

export const ROTATION_RULES = Object.freeze({
    // ── Carlotta (1107) ──────────────────────────────────────────────────────
    // Liberation "Era of New Wave" activates Twilight Tango. Inside that state,
    // Death Knell and Fatal Finale become available. Imminent Oblivion (Forte
    // heavy) needs full Substance, built primarily by skill/basic usage.
    1107: [
        { skillKey: 'liberation_death_knell',        requires: ['liberation'], gate: 'state',
          note: 'Available inside Twilight Tango (cast Resonance Liberation first).' },
        { skillKey: 'liberation_fatal_finale',       requires: ['liberation', 'liberation_death_knell'], gate: 'state',
          note: 'The finisher of the Twilight Tango sequence (after Liberation / Death Knell).' },
        { skillKey: 'skill_chromatic_splendor',      requires: ['skill'], gate: 'state',
          note: 'Follow-up to Resonance Skill — cast Art of Violence first.' },
        { skillKey: 'forte_heavy_imminent_oblivion', requires: ['skill', 'skill_chromatic_splendor', 'basic_necessary_measures_3'], gate: 'resource',
          note: 'Consumes full Substance — build it with Skill / Necessary Measures before casting.' },
        { skillKey: 'basic_necessary_measures_1',    requires: ['skill', 'skill_chromatic_splendor'], gate: 'resource',
          note: 'Replaces Basic Attack while Moldable Crystals are held (generated by Resonance Skill).' },
    ],

    // ── Hiyuki (1108) ────────────────────────────────────────────────────────
    // Two stances: Present Self (default) and Foreclaimed Self (entered via
    // Liberation). The Fore basics/heavies only exist in Foreclaimed Self.
    // Iai (Forte basic) consumes Snowforged stacks.
    1108: [
        { skillKey: 'basic_fore_1', requires: ['liberation_inward_vision', 'liberation_blade_liberation'], gate: 'form',
          note: 'Foreclaimed Self stance — entered via Resonance Liberation.' },
        { skillKey: 'heavy_fore',   requires: ['liberation_inward_vision', 'liberation_blade_liberation'], gate: 'form',
          note: 'Foreclaimed Self stance — entered via Resonance Liberation.' },
        { skillKey: 'heavy_bitterfrost_fore', requires: ['liberation_inward_vision', 'liberation_blade_liberation'], gate: 'form',
          note: 'Foreclaimed Self stance — entered via Resonance Liberation.' },
        { skillKey: 'forte_basic_iai', requires: ['skill_present', 'skill_jade_cleave', 'skill_petalfall'], gate: 'resource',
          note: 'Consumes Snowforged stacks — build them with Resonance Skill first.' },
    ],

    // ── Jinhsi (1304) ────────────────────────────────────────────────────────
    // Incarnation state (entered via Forte/Liberation) unlocks the Incarnation
    // basic and heavy chains plus the Illuminous Epiphany finishers.
    1304: [
        { skillKey: 'forte_basic_incarnation_basic_attack_1', requires: ['liberation', 'skill_overflowing_radiance'], gate: 'form',
          note: 'Incarnation state — entered via Resonance Skill / Liberation.' },
        { skillKey: 'forte_heavy_incarnation_heavy_attack',   requires: ['liberation', 'skill_overflowing_radiance'], gate: 'form',
          note: 'Incarnation state — entered via Resonance Skill / Liberation.' },
        { skillKey: 'forte_heavy_crescent_divinity',          requires: ['forte_basic_incarnation_basic_attack_4', 'liberation'], gate: 'form',
          note: 'Incarnation finisher — chains from the Incarnation basic sequence.' },
        { skillKey: 'forte_heavy_illuminous_epiphany_solar_flare',  requires: ['liberation'], gate: 'state',
          note: 'Empowered by Resonance Liberation (Purge of Light).' },
        { skillKey: 'forte_heavy_illuminous_epiphany_stella_glamor', requires: ['liberation'], gate: 'state',
          note: 'Empowered by Resonance Liberation (Purge of Light).' },
        { skillKey: 'skill_overflowing_radiance', requires: ['skill'], gate: 'state',
          note: 'Follow-up to Resonance Skill (Trailing Lights of Eons).' },
    ],

    // ── Changli (1205) ───────────────────────────────────────────────────────
    // True Sight has Capture → Conquest → Charge progression; Flaming Sacrifice
    // (Forte heavy) consumes all stacks built during the rotation.
    1205: [
        { skillKey: 'skill_true_sight_conquest', requires: ['skill_true_sight_capture'], gate: 'state',
          note: 'Second stage of True Sight — cast Capture first.' },
        { skillKey: 'skill_true_sight_charge',   requires: ['skill_true_sight_capture', 'skill_true_sight_conquest'], gate: 'state',
          note: 'Third stage of True Sight.' },
        { skillKey: 'forte_heavy_flaming_sacrifice', requires: ['liberation', 'skill_true_sight_capture'], gate: 'resource',
          note: 'Consumes accumulated stacks — build them before casting.' },
    ],

    // ── Cantarella (1607) ──────────────────────────────────────────────────────
    // Forte "Between Illusion and Reality" enters Mirage. In Mirage the basic
    // chain becomes Phantom Sting and the Resonance Skill becomes Flickering
    // Reverie. The Phantom Sting stages are sequential.
    1607: [
        { skillKey: 'skill_flickering_reverie', requires: ['skill_jolt', 'liberation_flowing_suffocation', 'forte_heavy_phantom_sting_1'], gate: 'form',
          note: 'Resonance Skill becomes Flickering Reverie while in Mirage.' },
        // Mirage's own text: "[Normal Attack] right after casting the skill
        // [that entered Mirage] to cast Basic Attack [Phantom Sting Stage 2]"
        // — so the Mirage-entering casts (Delusive Dive / S3 Liberation) grant
        // Stage 2 directly, alongside the normal Stage 1 chain.
        { skillKey: 'forte_heavy_phantom_sting_2', requires: ['forte_heavy_phantom_sting_1', 'basic_delusive_dive', 'liberation_flowing_suffocation'], gate: 'form',
          note: 'Second stage of the Phantom Sting chain — chains from Stage 1 or directly after entering Mirage (Delusive Dive / Flowing Suffocation).' },
        { skillKey: 'forte_heavy_phantom_sting_3', requires: ['forte_heavy_phantom_sting_2'], gate: 'form',
          note: 'Third stage of the Phantom Sting chain (Mirage).' },
        { skillKey: 'liberation_diffusion', requires: ['liberation_flowing_suffocation'], gate: 'state',
          note: 'Follow-up to the Resonance Liberation.' },
    ],

    // ── Phoebe (1506) ──────────────────────────────────────────────────────────
    // Forte "Radiant Invocation" consumes full Prayer to cast Absolution Litany
    // / Utter Confession. The Chamuel's Star sequence chains from the skill.
    1506: [
        { skillKey: 'forte_heavy_absolution_litany',   requires: ['skill', 'liberation', 'skill_chamuel_s_star_1'], gate: 'resource',
          note: 'Consumes full Prayer — build it with Skill / Liberation first.' },
        { skillKey: 'forte_heavy_utter_confession',    requires: ['skill', 'liberation', 'skill_chamuel_s_star_1'], gate: 'resource',
          note: 'Consumes full Prayer — build it with Skill / Liberation first.' },
        { skillKey: 'skill_chamuel_s_star_2', requires: ['skill_chamuel_s_star_1'], gate: 'state',
          note: 'Second stage of Chamuel\u2019s Star.' },
        { skillKey: 'skill_chamuel_s_star_3', requires: ['skill_chamuel_s_star_1', 'skill_chamuel_s_star_2'], gate: 'state',
          note: 'Third stage of Chamuel\u2019s Star.' },
    ],
});

// =============================================================================
// Lookups
// =============================================================================

/**
 * Get the rules for a resonator, or an empty array if none are defined.
 * @param {number|string} resonatorId
 * @returns {Array<object>}
 */
export function rulesForResonator(resonatorId) {
    return ROTATION_RULES[Number(resonatorId)] ?? [];
}

/**
 * Whether any gating rules exist for a resonator.
 * @param {number|string} resonatorId
 * @returns {boolean}
 */
export function hasRules(resonatorId) {
    return (ROTATION_RULES[Number(resonatorId)]?.length ?? 0) > 0;
}

// =============================================================================
// State definitions, keyed by resonator id.
// =============================================================================
//
// A state is a mode the character is in for part of the rotation, entered by a
// skill and exited by duration / a consuming skill / end of rotation. The
// rotation-state model uses these to compute which states are active at each
// step, which in turn resolves `inState` chain/inherent effects and (later)
// state-gated off-field and Tune Break interactions.
//
// StateDef shape:
//   { name, enter: { keys?, types? }, exit: { mode, keys?, types?, steps? } }
//
// exit.mode:
//   'persist'    — active until the rotation ends (most on-field forms)
//   'consumedBy' — ends when a listed key/type is cast
//   'duration'   — active for `steps` rotation steps (an approximation)

export const STATE_DEFS = Object.freeze({
    // Carlotta — Liberation "Era of New Wave" activates Twilight Tango; it
    // persists through the burst window (ends when she swaps off / it times out,
    // neither of which the single-character sim models → persist).
    1107: [
        { name: 'Twilight Tango',
          enter: { keys: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Brant — Intro "Applaud for Me!" grants [Interlude Applause]: "The next
    // Mid-air Attack begins at [Stage 2]. This effect ends when Brant lands
    // early or is switched out." One-shot license consumed by the first
    // mid-air attack (landing-early isn't modeled).
    1206: [
        { name: 'Interlude Applause',
          enter: { keys: ['intro'] },
          exit:  { mode: 'consumedBy', types: ['midair'] } },
    ],

    // Hiyuki — Liberation enters Foreclaimed Self (her empowered stance), which
    // replaces Present Self. Treated as persisting for the rest of the rotation.
    1108: [
        { name: 'Foreclaimed Self',
          enter: { keys: ['liberation_inward_vision', 'liberation_blade_liberation'] },
          exit:  { mode: 'persist' } },
        { name: 'Present Self',
          // Default stance — active from the start; ends once Foreclaimed Self begins.
          initiallyActive: true,
          enter: { keys: [], types: [] },
          exit:  { mode: 'consumedBy', keys: ['liberation_inward_vision', 'liberation_blade_liberation'] } },
    ],

    // Jinhsi — Incarnation state is entered via Liberation / the empowered skill
    // and powers the Incarnation basic/heavy chains.
    1304: [
        { name: 'Incarnation',
          enter: { keys: ['liberation', 'skill_overflowing_radiance'] },
          exit:  { mode: 'persist' } },
    ],

    // Aemeath — Stardust Resonance ONLY.
    //
    // A "Resonance Mode - Tune Rupture" state used to sit here, entered by any
    // forte_basic/forte_heavy cast. It was wrong twice over: a Resonance Mode is
    // a BUILD-LEVEL toggle (build.resonanceMode → effect.mode → modeGateOk), not
    // something a cast enters, and it is locked for the whole fight — so the
    // state lit up mid-rotation, and lit up in Fusion Burst mode too, because
    // the name was hardcoded to the other mode. Modes have their own gate; a
    // second path for the same concept could only ever disagree with the first.
    1210: [
        // "Casting this skill grants … Enter [Stardust Resonance] for 30s."
        // "## Stardust Resonance — Enhance the effect of Resonance Skill
        //  [Seraphic Duet]. This effect ends after [Seraphic Duet] is cast 2
        //  times." BOTH ends are stated, so both are modelled: the 30s timer or
        //  a budget of two Seraphic Duet casts, whichever runs out first. It
        //  selects her STRONGER Fusion Burst multiplier table
        //  (enemy-status.js AFFLICTION_TRIGGERS, whose `casts` matches `uses`).
        { name: 'Stardust Resonance',
          enter: { keys: ['liberation_heavenfall_edict_overdrive'] },
          exit:  { mode: 'secondsOrConsumedBy', seconds: 30, uses: 2,
                   keys: ['forte_heavy_seraphic_duet_encore', 'forte_heavy_seraphic_duet_overture'] } },
        // "[Heavenfall Edict - Overdrive] … Enter [Heavenfall Edict: Unbound]
        //  for 60s." / "When in [Heavenfall Edict - Unbound] and [Resonance
        //  Rate] reaches the limit, enter [Instant Response]." / "Casting
        //  [Heavy Attack - Aemeath: Charged II], [Heavy Attack - Mech: Charged
        //  II], or Resonance Liberation [Heavenfall Edict: Finale] ends
        //  [Instant Response]."
        //
        // Entered on the Overdrive cast, exactly as Stardust Resonance is: the
        // Resonance Rate limit is a resource the rotation is authored to reach,
        // and the state is nested inside Unbound's own 60s anyway. Both stated
        // ends are modelled — the 60s Unbound timer, or the first of the three
        // consuming casts.
        //
        // Three effects were resolving OFF for want of it, all of them large:
        // S1's +300% Crit. DMG and the inherent's +200% DMG Amplification on her
        // two Heavy Attacks, and S3's Fusion Burst infliction on the same casts
        // (enemy-status.js STATUS_APPLY_RULES).
        { name: 'Instant Response',
          enter: { keys: ['liberation_heavenfall_edict_overdrive'] },
          exit:  { mode: 'secondsOrConsumedBy', seconds: 60, uses: 1,
                   keys: ['heavy_aemeath_charged_ii', 'heavy_mech_charged_ii',
                          'liberation_heavenfall_edict_finale'] } },
    ],

    // Liberation/Forte STANCES whose kits state no timer (2026-08-01). Each is
    // entered by one cast and, per the project's standing reading of silence,
    // holds until something cancels it — which for a single rotation means
    // persist. Every one of these gates a chain effect that was resolving OFF
    // because the parser had no state to bind it to.
    //
    // Lingyang — Liberation "Strive: Lion's Vigor" grants [Lion's Vigor]
    // ("Lingyang gains 50% Glacio DMG Bonus"), with no stated duration.
    1104: [
        { name: "Lion's Vigor",
          enter: { keys: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Rover: Electro — "clear all [Electric Surge] to enter [Apex Resonance]",
    // from the HOLD form of Resonance Skill [Overshock]. Apex Resonance is what
    // unlocks his [Thrum of All Sounds] chain, so any Thrum key also proves he
    // is in it — which is why they count as entering keys too. His S5 ("Crit.
    // DMG is increased by 20% while in Apex Resonance") was the one state-gated
    // effect the tracker could not resolve before 2026-08-01.
    1309: [
        { name: 'Apex Resonance',
          enter: { keys: [
              'forte_heavy_overshock',
              'forte_heavy_thrum_of_all_sounds_spectro_1',
              'forte_heavy_thrum_of_all_sounds_havoc_1',
              'forte_heavy_thrum_of_all_sounds_aero',
              'forte_heavy_thrum_of_all_sounds_silencing_blade',
          ] },
          exit:  { mode: 'persist' } },
    ],

    // Mortefi — Liberation "Violent Finale" applies [Burning Rhapsody] to the
    // whole team (the Marcato coordinated-attack window). No stated duration.
    1204: [
        { name: 'Burning Rhapsody',
          enter: { keys: ['liberation_violent_finale_damage'] },
          exit:  { mode: 'persist' } },
    ],

    // Calcharo — Liberation enters [Deathblade Gear], which replaces his Basic
    // Attack and reclassifies Heavy/Dodge Counter as Liberation DMG. The kit
    // states the state ENDS (his next Intro is replaced afterwards) but never
    // says when, so persist.
    1301: [
        { name: 'Deathblade Gear',
          enter: { keys: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Camellya — "[Camellya] enters [Budding Mode] after casting [Ephemeral]."
    // A SECOND, unrelated state (OPEN-ITEMS 22, 2026-09-21): "Blossom Mode" and
    // "Budding Mode" read as synonyms and are not — the kit uses both names in
    // completely separate passages with no cross-reference. "Attack the
    // target... then enter [Blossom Mode]" (Resonance Skill [Crimson Blossom])
    // replaces Basic/Heavy with the Vining Waltz chain, Dodge Counter with
    // [Atonement], Resonance Skill with [Floral Ravage], and Jump with
    // [Vining Ronde] — a disjoint key set from Budding Mode's Sweet Dream
    // grant. "Blossom Mode ends after casting Resonance Skill [Floral
    // Ravage]" and "ends after using the [Levitator]" (no skill key exists for
    // the Levitator, so only the first exit is expressible) and "Jump ...
    // ends the Blossom Mode" (Vining Ronde). This is what
    // data/timing-overrides.json's needsStateModel entries for
    // skill_vining_waltz_3/skill_blazing_waltz actually need; the timing-
    // variant WIRING itself is not done here — see OPEN-ITEMS 22.
    1603: [
        { name: 'Budding Mode',
          enter: { keys: ['forte_heavy_ephemeral'] },
          exit:  { mode: 'persist' } },
        { name: 'Blossom Mode',
          enter: { keys: ['skill_crimson_blossom'] },
          exit:  { mode: 'consumedBy', keys: ['skill_floral_ravage', 'skill_vining_ronde'] } },
    ],

    // Rebecca — "Upon casting Resonance Skill or Intro Skill, Rebecca can
    // freely switch between the Huntress and Guts modes... By default,
    // Rebecca starts in the Huntress mode." (2026-09-21, OPEN-ITEMS 22). Each
    // mode has its own Skill AND Intro key that switches TO the other —
    // "It's Big Boomin' Time!" is cast IN Huntress and switches to Guts,
    // "Come 'n' Get Me!" is cast IN Guts and switches to Huntress — so each
    // pair is both the OTHER mode's enter and this mode's exit. Unblocks two
    // effects that read as zero today because nothing in the parser scans
    // Forte-circuit skill-tree node text: Huntress's flat +30% Crit. DMG and
    // Guts's 15% target DEF ignore (verified unparsed: zero "Huntress mode" /
    // "Guts mode" effect entries in wuwa-data.json). Binding those two
    // clauses to this state is a separate follow-up, not done here.
    1308: [
        { name: 'Huntress Mode',
          initiallyActive: true,
          enter: { keys: ['skill_come_n_get_me', 'intro_hey_leadhead_come_n_get_me'] },
          exit:  { mode: 'consumedBy', keys: ['skill_it_s_big_boomin_time', 'intro_yo_it_s_big_boomin_time'] } },
        { name: 'Guts Mode',
          enter: { keys: ['skill_it_s_big_boomin_time', 'intro_yo_it_s_big_boomin_time'] },
          exit:  { mode: 'consumedBy', keys: ['skill_come_n_get_me', 'intro_hey_leadhead_come_n_get_me'] } },
    ],

    // Lucy — "After casting Resonance Skill - Deadlock, Lucy enters
    // Algorithm Compaction... Lucy exits the Algorithm Compaction state after
    // casting Resonance Liberation - Netrunner or Resonance Liberation - Old
    // Net Deep Dive" (2026-09-21, OPEN-ITEMS 22). A clean enter/exit, unlike
    // Rebecca's pair — verified against her own reference rotation with no
    // contradiction (skill_deadlock -> the Compaction-only Thread-Shredding
    // basics and Threading heavies -> a Liberation cast, in that order).
    // NOT modelled: the kit's SECOND stated exit ("[Heavy Attack -
    // Multi-threading] is not followed up by one of [Basic/Skill/Intro/Tune
    // Break]" within an unstated window) has no shape in this module — the
    // same category of gap as Cantarella's unmodelled Trance-depletion exit.
    // This is the prerequisite for her intro_intro_skill_outdated_hallucination
    // key's needsStateModel entry (AM_SkillQte vs AM_Sp_SkillQte); the timing-
    // variant WIRING itself is not done here — see OPEN-ITEMS 22.
    1511: [
        { name: 'Algorithm Compaction',
          enter: { keys: ['skill_deadlock'] },
          exit:  { mode: 'consumedBy', types: ['liberation'] } },
    ],

    // Denia — two stances + the mutually-exclusive timed Entropy Shift pair,
    // all straight from her Liberation text (2026-07-05): she starts in
    // [Stagecraft Form] (her Intro "It's Been A While!" is Stagecraft-only and
    // opens the reference rotation). "Final Act - Stagecraft Form: after
    // performing this skill, obtain [Entropy Shift: Breakdown Form] for 12s,
    // then switch to [Breakdown Form]" / "Final Act - Breakdown Form: after
    // casting this skill, obtain [Entropy Shift: Stagecraft Form], which lasts
    // for 30s, and then switch to [Stagecraft Form]". Each Entropy Shift
    // "removes the [other] effect" → secondsOrConsumedBy on the other's enter
    // keys. Intro "Knock Knock" (Breakdown variant) also grants Entropy
    // Shift: Breakdown Form for 12s. The `entropy shift states` alias matches
    // her S6 "While in Entropy Shift states" gate exactly.
    1211: [
        { name: 'Stagecraft Form',
          initiallyActive: true,
          enter: { keys: ['liberation_final_act_breakdown_form'] },
          exit:  { mode: 'consumedBy', keys: ['liberation_final_act_stagecraft_form'] } },
        { name: 'Breakdown Form',
          enter: { keys: ['liberation_final_act_stagecraft_form'] },
          exit:  { mode: 'consumedBy', keys: ['liberation_final_act_breakdown_form'] } },
        { name: 'Entropy Shift: Breakdown Form',
          aliases: ['entropy shift states'],
          enter: { keys: ['liberation_final_act_stagecraft_form', 'intro_knock_knock'] },
          exit:  { mode: 'secondsOrConsumedBy', seconds: 12, keys: ['liberation_final_act_breakdown_form'] } },
        { name: 'Entropy Shift: Stagecraft Form',
          aliases: ['entropy shift states'],
          enter: { keys: ['liberation_final_act_breakdown_form'] },
          exit:  { mode: 'secondsOrConsumedBy', seconds: 30, keys: ['liberation_final_act_stagecraft_form', 'intro_knock_knock'] } },
    ],

    // Phrolova — Liberation "Waltz of Forsaken Depths" enters Maestro state (24s).
    // All liberation-type keys in the autoSkillMap are cast WITHIN Maestro; the
    // first liberation cast marks Maestro's activation.
    1608: [
        { name: 'Maestro',
          enter: { types: ['liberation'] },
          exit:  { mode: 'persist' } },
    ],

    // Ciaccona — Liberation "Singer's Triple Cadenza" enters Recital.
    // Recital persists until she switches back on-field (modelled as persist).
    1407: [
        { name: 'Recital',
          enter: { keys: ['liberation_improvised_symphonic_poem_skill'] },
          exit:  { mode: 'persist' } },
    ],

    // Phoebe — Absolution / Confession, entered via the Forte heavy attacks that
    // consume full Prayer. Per her own kit text ("Absolution and Confession
    // cannot coexist. Entering into one will end the other" / "When Divine
    // Voice is exhausted, Phoebe will not exit the Absolution or Confession
    // status") — mutually exclusive, each ended only by the other being
    // entered (Divine Voice itself isn't modeled, so re-entry gating is
    // skipped; the consumedBy relationship is what matters for the timeline).
    // Neither is active at rotation start (she begins in neither status).
    1506: [
        { name: 'Absolution',
          enter: { keys: ['forte_heavy_absolution_litany'] },
          exit:  { mode: 'consumedBy', keys: ['forte_heavy_utter_confession'] } },
        { name: 'Confession',
          enter: { keys: ['forte_heavy_utter_confession'] },
          exit:  { mode: 'consumedBy', keys: ['forte_heavy_absolution_litany'] } },
    ],

    // Cantarella — Mirage, entered via Heavy Attack Delusive Dive (base kit) or
    // Resonance Liberation Flowing Suffocation (S3 enhancement). Per her own
    // kit text: "Mirage lasts for 8s. Mirage ends when Trance is depleted." —
    // a REAL timed expiry (exit.mode 'seconds', not the step-count 'duration'
    // approximation), confirmed by the maintainer 2026-06-27. The Trance-
    // depletion exit isn't modeled (Trance is an unmodeled resource); the timer
    // is the trackable part.
    1607: [
        { name: 'Mirage',
          enter: { keys: ['basic_delusive_dive', 'liberation_flowing_suffocation'] },
          exit:  { mode: 'seconds', seconds: 8 } },
    ],

    // Jingran — Resonance Liberation "Burial of Thousand Souls" states its own
    // entry and its own timer: "Enter the Yinghuo state for 15s" (the skill's
    // param[5]). A REAL timed expiry, so 'seconds' rather than 'persist'.
    // His S2 gates a second +46% multiplier increase on being in it, and an
    // effect naming a state the resonator lacks can never fire — it would have
    // shipped silently dead. The Fire-of-Life clearing that Yinghuo's end
    // performs is not modelled (that gauge has no RESOURCE_DEFS entry yet), so
    // this def carries the window only.
    1212: [
        { name: 'Yinghuo',
          enter: { keys: ['liberation_burial_of_thousand_souls'] },
          exit:  { mode: 'seconds', seconds: 15 } },
    ],

    // Lucilla — "Clear As Day Buff" (S2.0's Déjà Vu / Resonance-Mode-gated
    // enhancement): entered by casting Liberation "Clear As Day" itself, per
    // her own kit text "continue to exist when in Reminiscence [entered by
    // the same Liberation cast, per 'Clear As Day' deals DMG and enters
    // Reminiscence] and last for 30s after Reminiscence ends [per 'Letting
    // It Go' base kit text: 'Casting Letting It Go ends Reminiscence']." Mode-
    // switching as an additional exit isn't modeled — confirmed safe by the
    // maintainer 2026-06-27: Resonance Mode is locked for the whole sim/team
    // comp, never switches mid-rotation.
    1109: [
        { name: 'Clear As Day Buff',
          enter: { keys: ['liberation'] },
          exit:  { mode: 'consumedByThenSeconds', keys: ['liberation_letting_it_go'], seconds: 30 } },
    ],
});

/**
 * State definitions for a resonator, or an empty array if none.
 * @param {number|string} resonatorId
 * @returns {Array<object>}
 */
export function stateDefsForResonator(resonatorId) {
    return STATE_DEFS[Number(resonatorId)] ?? [];
}

// =============================================================================
// Timing-variant selection rules, keyed by resonator id (2026-09-21, OPEN-ITEMS 22).
// =============================================================================
//
// A handful of skillMap keys have TWO real, measured timings and no kit-stated
// name to pick between them by — the game authors the animation differently
// depending on what the resonator was doing the instant before the cast. Both
// candidates are preserved as `step.variants` (preprocess.mjs, only for keys
// data/timing-overrides.json flags `needsStateModel`); this table says which
// one applies.
//
//   { whenPrevSkillType: string, variantMontage: string }   — rotation order
//   { whenState: string,         variantMontage: string }   — a STATE_DEFS state
//
// `whenPrevSkillType` matches the PRECEDING rotation step's mechanical
// skillType — cheap and precedented (rotation-graph.js's STAGE_GRANTS `after`
// mechanism already reads `rotation[i-1]` the same way) — deliberately NOT a
// STATE_DEFS lookup: elevation ("was the previous action airborne?") is not a
// kit-granted, named, entered/exited mode, and the two mechanisms answer
// different questions. `variantMontage` is matched against each variant's
// `montage` (a suffix test — the extracted path carries the character's own
// asset directory, the rule only needs the filename).
//
// `whenState` names a STATE_DEFS state instead, for the case where the game
// really does author one key two ways depending on a kit-granted mode. It is
// resolved from the state timeline, which creates an ORDERING problem worth
// stating: `computeStepTimes` resolves durations BEFORE
// `computeStateTimeline` exists (the timeline takes step times as INPUT, to
// expire a 'seconds' state), so the two consumers read the state from
// different calls of the same function — the pre-pass runs it WITHOUT times
// (which its own docstring blesses: "callers that don't have timing info may
// omit it"), the main walk reads the full timeline. Those two agree only for a
// state whose exit needs no clock, so a `whenState` rule may ONLY name a state
// whose exit mode is time-independent ('persist', 'consumedBy', 'duration').
// `tests/timing-variant.test.mjs` enforces that, because a 'seconds' state
// would read persist-like in the pre-pass and expire in the walk — one cast
// getting two different durations from one rotation.
//
// Zhezhi's Heavy Attack Conjuration is the one roster case with two verified
// candidates sharing one damage id (measured in data/actionable-times.json,
// 2026-09-21): AM_Attack05_Air.uasset (0.567s, entered from mid-air) and
// AM_Attack05.uasset (1.180s, the ground default `pinnedMontage` already
// selects). Two of Conjuration's five stated entry points — Stroke of Genius
// and Creation's Zenith — are themselves airborne-capable but carry
// `skillType: 'forte_heavy'`, not `'midair'`, so a chain reaching Conjuration
// through one of THEM while airborne still falls through to the ground
// default; a known, conservative approximation (no physics model exists to
// do better), not a defect this table can close.
//
// Lucy's Intro is the one verified `whenState` case (2026-10-02). Her kit
// states the Intro behaves differently inside the state in its own text ("If
// Lucy is NOT in Algorithm Compaction after casting this skill … cast Basic
// Attack Stage N. If Lucy IS in Algorithm Compaction after casting this skill
// … cast Basic Attack - Thread Shredding Stage N"), and the asset names are
// their own second witness: of her 23 measured keys, the `AM_Sp_` prefix
// appears on exactly the NINE that Algorithm Compaction replaces (Thread
// Shredding 1-4, Single/Dual/Multi-threading, and the Compaction mid-air and
// dodge-counter) and on nothing else — so `AM_Sp_SkillQte` (1.067s) is the
// Compaction authoring of `AM_SkillQte` (0.733s), which is the default.
//
// THREE of the six needsStateModel resonators have no entry here, each for a
// measured reason rather than for want of effort (OPEN-ITEMS 22):
// → Brant's four keys (midair_mid_air_attack_1..4): three have exactly one
//   montage candidate in the export (nothing to select between) and the
//   fourth's three candidates are variants of the SAME airborne bullet, not a
//   ground/air split.
// → Camellya's two (skill_vining_waltz_3, skill_blazing_waltz): both keys
//   share the same two candidates and ALREADY hold the right one each —
//   `AM_Attack03_Ex` (1.150s) for the tap stage 3, `AM_Attack03_Ex_Loop`
//   (1.863s) for the hold that casts Blazing Waltz. Blossom Mode is a
//   CASTABILITY precondition for the whole Waltz chain, not a selector
//   between those two authorings.
// → Rebecca's two Intro keys: likewise already resolved, and by a
//   `pinnedMontage` each (`AM_QTE_S` 1.533s for the Huntress intro,
//   `AM_QTE_M_Start01` 1.158s for the Guts one). Her Huntress/Guts mode
//   decides WHICH OF THE TWO KEYS is cast, which is an `introKeyFor`
//   question, not a per-key variant one.
export const TIMING_VARIANT_RULES = Object.freeze({
    1105: {
        forte_heavy_ha_conjuration: { whenPrevSkillType: 'midair', variantMontage: 'AM_Attack05_Air.uasset' },
    },
    1511: {
        intro_intro_skill_outdated_hallucination: { whenState: 'Algorithm Compaction', variantMontage: 'AM_Sp_SkillQte.uasset' },
    },
});

// Exit modes a `whenState` rule may depend on: those the state timeline
// resolves identically with and without step times. See the ordering note
// above — this is the invariant that keeps the pre-pass and the main walk
// from disagreeing about one cast's duration.
export const TIME_INDEPENDENT_EXIT_MODES = Object.freeze(['persist', 'consumedBy', 'duration']);

/**
 * The variant (if any) this key's timing should use at this point in the
 * rotation. Returns null when no rule applies, the key carries no rule, or the
 * rule's condition does not hold — every caller then keeps the key's own
 * already-chosen fields, which is the correct, unchanged behaviour for the
 * other ~1,100 skillMap keys with no rule at all.
 *
 * A `whenPrevSkillType` rule needs a previous step, so it never fires at
 * i === 0. A `whenState` rule has no such restriction: a state can be
 * `initiallyActive` (Rebecca's Huntress, Hiyuki's Present Self), so step 0 is
 * a legitimate match.
 *
 * @param {number|string} resonatorId
 * @param {string} key
 * @param {object} skillDef      — skillMap[key], carries `.variants`
 * @param {string[]} rotation
 * @param {number} i             — index of `key` within `rotation`
 * @param {object} skillMap
 * @param {Set<string>} [activeStates] — states active entering step i
 * @returns {object|null} a variant object ({ stepDuration, resolvesAt, freezeTime, montage })
 */
export function timingVariantFor(resonatorId, key, skillDef, rotation, i, skillMap, activeStates = null) {
    if (!skillDef?.variants?.length) return null;
    const rule = TIMING_VARIANT_RULES[Number(resonatorId)]?.[key];
    if (!rule) return null;
    if (rule.whenPrevSkillType != null) {
        if (i <= 0) return null;
        if (skillMap[rotation[i - 1]]?.skillType !== rule.whenPrevSkillType) return null;
    }
    if (rule.whenState != null && !stateActive(activeStates, rule.whenState.toLowerCase())) return null;
    return skillDef.variants.find(variant => variant.montage?.endsWith(rule.variantMontage)) ?? null;
}

// =============================================================================
// Stage-entry grants, keyed by resonator id (2026-07-05).
// =============================================================================
//
// The generic stage-ordering check (rotation-graph.js) assumes a staged family
// (Basic 1→2→3…) is strictly sequential. Many kits explicitly BREAK that:
// "Normal Attack right after casting this skill to cast [Basic Attack Stage N]".
// Each entry below is verified against the kit text in wuwa-data.json (the
// quoted grant lives in the GRANTING skill's own description).
//
// Grant shape — a stage step is exempt from the N−1 requirement when ANY of:
//   free:     true      — the family is not actually sequential (e.g. charge
//                         levels named "Lv. 1–3") or has hold/direct entry.
//   after:    string[]  — the IMMEDIATELY preceding rotation step is one of
//                         these keys ("right after / shortly after casting").
//   state:    string    — the named state (STATE_DEFS) is active entering the
//                         step (one-shot licenses like Brant's Interlude
//                         Applause, consumed by the granted cast itself).
//   resource: {name, atLeast} — the curated resource (RESOURCE_DEFS) has
//                         reached the threshold at this step.
//   note:     string    — human copy for the grant chip / tooltip.

export const STAGE_GRANTS = Object.freeze({
    // Brant — Intro "Applaud for Me!" grants [Interlude Applause]: "The next
    // Mid-air Attack begins at [Stage 2]." A persistent one-shot license (ends
    // on landing/switch — unmodeled), so it survives intermediate casts.
    1206: {
        midair_mid_air_attack_2: {
            state: 'interlude applause',
            note: 'Intro (Applaud for Me!) grants Interlude Applause — the next Mid-air Attack begins at Stage 2.',
        },
    },

    // Hiyuki — Dodge Counter (Present): "[Normal Attack] within a certain
    // period after casting this skill to perform [Basic Attack - Present Self
    // Stage 3]"; all three Resonance Skills + the Intro: "hold [Normal Attack]
    // within a certain period after casting this skill to perform [Basic
    // Attack - Present Self Stage 3]"; Intro (Foreclaimed): "[Normal Attack]
    // … to cast [Basic Attack - Foreclaimed Self Stage 2]"; Heavy (Fore) →
    // Fore Stage 2; Bitterfrost → "chain into [Basic Attack - Foreclaimed
    // Self Stage 4] instead"; Dodge Counter (Fore) → Fore Stage 3.
    1108: {
        basic_present_3: {
            after: ['basic_dodge_counter_present', 'skill_present', 'skill_jade_cleave', 'skill_petalfall', 'intro'],
            note: 'Dodge Counter / Resonance Skills / Intro chain into Basic - Present Self Stage 3.',
        },
        basic_fore_2: {
            after: ['heavy_fore', 'intro'],
            note: 'Heavy Attack (Foreclaimed) / Intro chain into Basic - Foreclaimed Self Stage 2.',
        },
        basic_fore_3: {
            after: ['basic_dodge_counter_fore'],
            note: 'Dodge Counter (Foreclaimed) chains into Basic - Foreclaimed Self Stage 3.',
        },
        basic_fore_4: {
            after: ['heavy_bitterfrost_fore'],
            note: 'Bitterfrost Heavy chains into Basic - Foreclaimed Self Stage 4.',
        },
    },

    // Lucilla — Mid-air Attack / Compensate / Spotlight: "[Normal Attack]
    // shortly after casting this skill to cast [Basic Attack Stage 2]";
    // Mid-air Reminiscence → Tracing Forms Stage 2; Dodge Counter
    // Reminiscence → Tracing Forms Stage 3.
    1109: {
        basic_basic_attack_2: {
            after: ['midair_mid_air_attack', 'skill_compensate', 'skill_spotlight'],
            note: 'Mid-air Attack / Compensate / Spotlight chain into Basic Attack Stage 2.',
        },
        liberation_tracing_forms_2: {
            after: ['midair_reminiscence'],
            note: 'Mid-air Attack - Reminiscence chains into Basic - Tracing Forms Stage 2.',
        },
        liberation_tracing_forms_3: {
            after: ['liberation_dodge_counter_reminiscence'],
            note: 'Dodge Counter - Reminiscence chains into Basic - Tracing Forms Stage 3.',
        },
    },

    // Lupa — "After [Dodge Counter], Basic Attack [Starfall], Resonance Skill
    // [Shewolf's Hunt], or Resonance Skill [Feral Fang], Normal Attack in
    // time to cast [Basic Attack Stage 2]."
    1207: {
        basic_2: {
            after: ['basic_dodge_counter', 'basic_starfall', 'skill_skill_damage', 'skill_feral_fang'],
            note: 'Dodge Counter / Starfall / Shewolf’s Hunt / Feral Fang chain into Basic Attack Stage 2.',
        },
    },

    // Galbrena — Intro: "Normal Attack right after casting this skill to
    // perform [Basic Attack Stage 2]"; Basic 4 loops: "Normal Attack right
    // after performing [Basic Attack Stage 4] to perform [Basic Attack Stage
    // 2]"; Liberation: "Normal Attack after casting Resonance Liberation to
    // cast [Basic Attack Stage 2]. While in [Demon Hypostasis], cast [Basic
    // Attack - Seraphic Execution Stage 2] instead."; Volley of Death 1 →
    // Basic 2 / Volley 2-3 → Basic 3; Plunging Attack → Basic 3; Dodge
    // Counter (Blood for Blood) → Basic 4; Intro also holds into Volley
    // Stage 2 / Flamewing Verdict Stage 2 (Demon Hypostasis); Seraphic 5
    // loops to 3; Flamewing Verdict 1 → Seraphic 2, 2-3 → Seraphic 3.
    1208: {
        basic_basic_attack_2: {
            after: ['intro_intro_skill_hellflare_overload', 'basic_basic_attack_4', 'liberation_hellfire_absolution', 'heavy_volley_of_death_1'],
            note: 'Intro / Basic 4 loop / Liberation / Volley of Death Stage 1 chain into Basic Attack Stage 2.',
        },
        basic_basic_attack_3: {
            after: ['heavy_volley_of_death_2', 'heavy_volley_of_death_3', 'midair_ashfall_barrage_plunging_attack'],
            note: 'Volley of Death Stage 2/3 / Plunging Attack chain into Basic Attack Stage 3.',
        },
        basic_basic_attack_4: {
            after: ['basic_dodge_counter_blood_for_blood'],
            note: 'Dodge Counter (Blood for Blood) chains into Basic Attack Stage 4.',
        },
        heavy_volley_of_death_2: {
            after: ['intro_intro_skill_hellflare_overload'],
            note: 'Hold Normal Attack after the Intro casts Volley of Death Stage 2.',
        },
        forte_basic_seraphic_execution_2: {
            after: ['liberation_hellfire_absolution', 'intro_intro_skill_hellflare_overload', 'forte_heavy_flamewing_verdict_1'],
            note: 'Liberation / Intro / Flamewing Verdict Stage 1 chain into Seraphic Execution Stage 2 (Demon Hypostasis).',
        },
        forte_basic_seraphic_execution_3: {
            after: ['forte_basic_seraphic_execution_5', 'forte_heavy_flamewing_verdict_2', 'forte_heavy_flamewing_verdict_3'],
            note: 'Seraphic Execution loops 5 → 3; Flamewing Verdict Stage 2/3 chain into Seraphic Stage 3.',
        },
        forte_heavy_flamewing_verdict_2: {
            after: ['intro_intro_skill_hellflare_overload'],
            note: 'Hold Normal Attack after the Intro (in Demon Hypostasis) casts Flamewing Verdict Stage 2.',
        },
    },

    // Mornye — Dodge Counter → Basic 2; Mid-air Attack → Basic 3; Dodge
    // Counter (Wide Field Observation Mode) → WFO Basic Stage 3.
    1209: {
        basic_basic_attack_2: {
            after: ['basic_dodge_counter'],
            note: 'Dodge Counter chains into Basic Attack Stage 2.',
        },
        basic_basic_attack_3: {
            after: ['midair_mid_air_attack'],
            note: 'Mid-air Attack chains into Basic Attack Stage 3.',
        },
        basic_wide_field_observation_mode_3: {
            after: ['basic_dodge_counter_wide_field_observation_mode'],
            note: 'Dodge Counter (Wide Field Observation Mode) chains into WFO Basic Stage 3.',
        },
    },

    // Aemeath — Intro: "[Resonance Skill] … shortly after casting this skill
    // to cast [Basic Attack - Mech Stage 3] automatically"; Liberation
    // Overdrive: "[Normal Attack] shortly after casting this skill to cast
    // [Basic Attack - Mech Stage 2]"; Seraphic Duet Overture: "Switch into the
    // Mech form … [Normal Attack] within a certain period of time to cast
    // [Basic Attack - Mech Stage 2]"; Seraphic Duet Encore: "Switch back to
    // Aemeath … [Normal Attack] shortly afterward to cast [Basic Attack -
    // Aemeath Stage 2]"; Heavy Charged II → Aemeath Stage 3.
    1210: {
        skill_mech_3: {
            after: ['intro_debut_of_meteoric_radiance'],
            note: 'Intro (Debut of Meteoric Radiance): Form Switch shortly after casts Basic - Mech Stage 3.',
        },
        skill_mech_2: {
            after: ['liberation_heavenfall_edict_overdrive', 'forte_heavy_seraphic_duet_overture'],
            note: 'Liberation Overdrive / Seraphic Duet: Overture chain into Basic - Mech Stage 2.',
        },
        basic_aemeath_2: {
            after: ['forte_heavy_seraphic_duet_encore'],
            note: 'Seraphic Duet: Encore switches back to Aemeath and chains into Basic - Aemeath Stage 2.',
        },
        basic_aemeath_3: {
            after: ['heavy_mech_charged_ii'],
            note: 'Heavy Attack Charged II chains into Basic - Aemeath Stage 3.',
        },
    },

    // Denia — Intro "It's Been A While!": "[Normal Attack] after casting this
    // skill to cast [Basic Attack - Stagecraft Form Stage 4]"; Dodge Counter
    // (Stagecraft): same grant. Dodge Counter (Breakdown): "[Normal Attack]
    // shortly after casting this skill to perform [Basic Attack - Breakdown
    // Form Stage 4] or [Mid-air Attack - Breakdown Form Stage 4]."
    1211: {
        basic_stagecraft_form_4: {
            after: ['intro_it_s_been_a_while', 'basic_dodge_counter_stagecraft_form'],
            note: 'Intro (It’s Been A While!) / Dodge Counter chain directly into Stagecraft Stage 4.',
        },
        basic_breakdown_form_4: {
            after: ['basic_dodge_counter_breakdown_form'],
            note: 'Dodge Counter (Breakdown) chains into Basic - Breakdown Form Stage 4.',
        },
        midair_breakdown_form_4: {
            after: ['basic_dodge_counter_breakdown_form'],
            note: 'Dodge Counter (Breakdown) chains into Mid-air - Breakdown Form Stage 4.',
        },
    },

    // Augusta — Heavy (Steelclash): "[Normal Attack] shortly after performing
    // Heavy Attack to perform [Basic Attack Stage 2]" (incl. the dodge-counter
    // Steelclash variant — same move).
    1306: {
        basic_2: {
            after: ['heavy_heavy_attack_steelclash', 'heavy_dodge_counter_heavy_attack_steelclash'],
            note: 'Heavy Attack (Steelclash) chains into Basic Attack Stage 2.',
        },
    },

    // Yinlin — MAINTAINER-VERIFIED IN-GAME (2026-07-05), not described in any
    // kit text: her Intro chains directly into Basic Attack Stage 4 (Prydwen's
    // community rotation uses it; confirmed correct in-game).
    1302: {
        basic_4: {
            after: ['intro'],
            note: 'Maintainer-verified in-game: Intro chains directly into Basic Attack Stage 4 (undocumented).',
        },
    },

    // Buling — Skill: "Right after casting [Resonance Skill], [Normal Attack]
    // to perform [Basic Attack Stage 4]."
    1307: {
        basic_4: {
            after: ['skill_thunder_talisman'],
            note: 'Right after Resonance Skill (Thunder Talisman), Normal Attack performs Basic Attack Stage 4.',
        },
    },

    // Rebecca — Skill "It's Big Boomin' Time!" / Intro "Yo, It's Big Boomin'
    // Time!": "[Normal Attack] shortly after casting this skill to follow up
    // with [Basic Attack - Guts] Stage 2."
    1308: {
        basic_guts_2: {
            after: ['skill_it_s_big_boomin_time', 'intro_yo_it_s_big_boomin_time'],
            note: 'It’s Big Boomin’ Time! (skill or intro) chains into Basic - Guts Stage 2.',
        },
    },

    // Rover: Aero — Heavy: "[Normal Attack] right after casting the skill to
    // perform [Basic Attack Stage 3] directly"; Mid-air: "[Normal Attack]
    // shortly after landing to cast [Basic Attack Stage 4]."
    1406: {
        basic_3: {
            after: ['heavy_heavy_attack'],
            note: 'Heavy Attack chains into Basic Attack Stage 3 directly.',
        },
        basic_4: {
            after: ['midair_mid_air_attack'],
            note: 'Mid-air Attack (after landing) chains into Basic Attack Stage 4.',
        },
    },

    // Ciaccona — Intro: "Follow up with Basic Attack in time to cast Basic
    // Attack Stage 3"; Mid-air 2: "Normal Attack after Mid-air Attack Stage 2
    // to cast Basic Attack Stage 4"; Dodge Counter: "Normal Attack in time to
    // cast Basic Attack Stage 2."
    1407: {
        basic_2: {
            after: ['basic_dodge_counter'],
            note: 'Dodge Counter chains into Basic Attack Stage 2.',
        },
        basic_3: {
            after: ['intro'],
            note: 'Intro (Roaming with the Wind) chains into Basic Attack Stage 3.',
        },
        basic_4: {
            after: ['midair_mid_air_attack_2'],
            note: 'Mid-air Attack Stage 2 chains into Basic Attack Stage 4.',
        },
    },

    // Iuno — Moonbow Dodge Counter: "When in [Lunar Cycle - New Moon], Normal
    // Attack again shortly after performing this skill to cast Moonbow -
    // Basic Attack Stage 3." (The Moonring Dodge Counter grant exists in text
    // but has no skill-map key — see docs/COMBO-ENTRY-CURATION.md.)
    1410: {
        basic_moonbow_basic_attack_3: {
            after: ['basic_moonbow_dodge_counter'],
            note: 'Moonbow Dodge Counter chains into Moonbow Basic Attack Stage 3.',
        },
    },

    // Cartethyia — Intro: "[Normal Attack] shortly after … to perform [Basic
    // Attack - Cartethyia Stage 2]"; Mid-air Fleurdelys Stage 3 has DIRECT
    // hold entry ("While airborne, hold [Normal Attack] to cast [Mid-air
    // Attack - Fleurdelys Stage 3]"); Mid-air 3 / May Tempest chain into
    // Fleurdelys Basic Stage 3.
    1409: {
        basic_2: {
            after: ['intro_sword_to_mark_tide_s_trace'],
            note: 'Intro (Sword to Mark Tide’s Trace) chains into Basic - Cartethyia Stage 2.',
        },
        forte_heavy_mid_air_attack_3: {
            free: true,
            note: 'While airborne, hold Normal Attack casts Mid-air - Fleurdelys Stage 3 directly.',
        },
        forte_basic_basic_attack_3: {
            after: ['forte_heavy_mid_air_attack_3', 'forte_heavy_may_tempest_break_the_tides'],
            note: 'Mid-air Fleurdelys Stage 3 / May Tempest Break the Tides chain into Basic - Fleurdelys Stage 3.',
        },
    },

    // Qiuyuan — Intro: "Within a certain period of time after casting this
    // skill, [Normal Attack] to perform Basic Attack [Thus Spoke the Blade:
    // Inkwash] Stage 3."; Heavy: "[Normal Attack] within a certain period of
    // time after casting this skill to perform … Inkwash Stage 4."
    1411: {
        forte_heavy_thus_spoke_the_blade_inkwash_3: {
            after: ['intro_skill_damage'],
            note: 'Intro chains into Thus Spoke the Blade: Inkwash Stage 3.',
        },
        forte_heavy_thus_spoke_the_blade_inkwash_4: {
            after: ['heavy_heavy_attack'],
            note: 'Heavy Attack chains into Thus Spoke the Blade: Inkwash Stage 4.',
        },
    },

    // Shorekeeper — Skill (Dim Star Butterfly): "Follow up with [Basic
    // Attack] in time to start the Basic Attack cycle from [Stage 2]."
    1505: {
        basic_2: {
            after: ['skill_dim_star_butterfly'],
            note: 'Dim Star Butterfly chains into the Basic cycle starting at Stage 2.',
        },
    },

    // Sigrika — Intro: "[Normal Attack] shortly after casting [Intro Skill] to
    // cast [Basic Attack Stage 2]"; plus the Full Stop cycle rule: "When
    // Sigrika has at least 50 of [Full Stop], her Basic Attack cycle starts
    // from Stage 2." (Full Stop tracked via RESOURCE_DEFS.)
    1412: {
        basic_basic_attack_2: {
            after: ['intro', 'heavy_heavy_attack'],
            resource: { name: 'Full Stop', atLeast: 50 },
            note: 'Intro / Heavy chain into Basic Stage 2; with ≥50 Full Stop her Basic cycle always starts at Stage 2.',
        },
    },

    // Zani — Skill: "[Normal Attack] within a certain time to perform [Basic
    // Attack Stage 3]".
    1507: {
        basic_3: {
            after: ['skill_standard_defense_protocol'],
            note: 'Resonance Skill (Standard Defense Protocol) chains into Basic Attack Stage 3.',
        },
    },

    // Chisa — Intro: "[Normal Attack] shortly after casting this skill to cast
    // [Basic Attack Stage 2]" (non-Chainsaw) / "[Sawring - Blitz Stage 2]"
    // (Chainsaw Mode); Serrated Loop: "[Normal Attack] shortly after casting
    // this skill to cast [Sawring - Blitz Stage 2]".
    1508: {
        // Moment of Nihility states the same chain-in the Intro does, in its own
        // node text: "While not in Chainsaw Mode, [Normal Attack] shortly after
        // casting this skill to cast Basic Attack Stage 2." Only `intro` was
        // listed, so her arabwuwa opener — Liberation straight into Basic 2 —
        // read as an illegal sequence.
        basic_2: {
            after: ['intro', 'liberation'],
            note: 'Intro (Reverberance — Return) and Resonance Liberation (Moment of Nihility) both chain into Basic Attack Stage 2.',
        },
        // Eye of Unraveling: "While not in Chainsaw Mode, after casting this
        // skill, [Normal Attack] on the ground or use [Normal Attack] in mid-air
        // to cast Rending Lunge." That is the opener's first two steps.
        basic_rending_lunge: {
            after: ['basic_2', 'skill_eye_of_unraveling', 'basic_dodge_counter'],
            note: 'Basic Attack Stage 2, Eye of Unraveling and Dodge Counter all chain into Rending Lunge.',
        },
        forte_heavy_sawring_blitz_2: {
            after: ['skill_serrated_loop', 'intro'],
            note: 'Serrated Loop / Intro (in Chainsaw Mode) chain into Sawring - Blitz Stage 2.',
        },
    },

    // Lynae — "Spark Collision Lv. 1–3" are CHARGE LEVELS of one hold attack
    // (Lumiflow ratio picks the level), not combo stages: "Upon releasing
    // Normal Attack or when [Lumiflow] is full, Lynae casts Spark Collision of
    // varying strengths based on the ratio of [Lumiflow]". Lynae-Style
    // Palettes → Basic Stage 2; Additive Color / To a Vivid Tomorrow /
    // Iridescent Splash / Visual Impact → Kaleidoscopic Parade Basic Stage 2.
    1509: {
        basic_spark_collision_lv_2: { free: true, note: 'Spark Collision levels are charge strengths, not combo stages.' },
        basic_spark_collision_lv_3: { free: true, note: 'Spark Collision levels are charge strengths, not combo stages.' },
        basic_basic_attack_2: {
            after: ['skill_lynae_style_palettes'],
            note: 'Lynae-Style Palettes chains into Basic Attack Stage 2.',
        },
        basic_kaleidoscopic_parade_basic_attack_2: {
            after: ['skill_additive_color', 'liberation_to_a_vivid_tomorrow', 'forte_basic_iridescent_splash', 'forte_basic_visual_impact'],
            note: 'Additive Color / To a Vivid Tomorrow / Iridescent Splash / Visual Impact chain into Kaleidoscopic Parade Basic Stage 2.',
        },
    },

    // Luuk Herssen — Dodge Counter: "[Normal Attack] right after casting this
    // skill to cast [Basic Attack Stage 3]." Mid-air stages 2–3 exist only as
    // named Scythe variants (no trailing digit → invisible to the stage
    // parser), so Stage 4's real predecessors are curated here.
    1510: {
        basic_basic_attack_3: {
            after: ['basic_ground_dodge_counter'],
            note: 'Dodge Counter chains into Basic Attack Stage 3.',
        },
        midair_mid_air_attack_4: {
            after: ['midair_mid_air_attack_3_scythe_dissection', 'midair_mid_air_attack_3_scythe_resction'],
            note: 'Mid-air Stage 3 exists as the Scythe Dissection/Resection variants — either chains into Stage 4.',
        },
    },

    // Lucy — Pulse Interference → Basic 2; Heavy 1 → Basic 3; Dodge Counter →
    // Basic 4; Heavy Stage 2 reachable by holding after Basic 3 / Dodge
    // Counter / Pulse Interference ("Hold [Normal Attack] shortly after …
    // lands to cast [Heavy Attack Stage 2]"); the three Threading heavies and
    // Deadlock chain into Thread Shredding Stage 2.
    1511: {
        basic_basic_attack_2: {
            after: ['skill_pulse_interference'],
            note: 'Resonance Skill (Pulse Interference) chains into Basic Attack Stage 2.',
        },
        basic_basic_attack_3: {
            after: ['heavy_heavy_attack_1'],
            note: 'Heavy Attack Stage 1 chains into Basic Attack Stage 3.',
        },
        basic_basic_attack_4: {
            after: ['basic_dodge_counter'],
            note: 'Dodge Counter chains into Basic Attack Stage 4.',
        },
        heavy_heavy_attack_2: {
            after: ['basic_basic_attack_3', 'basic_dodge_counter', 'skill_pulse_interference'],
            note: 'Hold after Basic 3 / Dodge Counter / Pulse Interference casts Heavy Attack Stage 2 directly.',
        },
        basic_thread_shredding_2: {
            after: ['heavy_single_threading', 'heavy_dual_threading', 'heavy_multithreading', 'skill_deadlock'],
            note: 'Single/Dual/Multi-threading heavies and Deadlock chain into Thread Shredding Stage 2.',
        },
    },

    // Danjin — MAINTAINER-VERIFIED IN-GAME (2026-07-05), not described in kit
    // text: her Resonance Skill weaves INTO the Basic chain (the kit only
    // documents the reverse direction, "after Basic Attack 2 … use Resonance
    // Skill"). Right after Carmine Gleam, Normal Attack lands at Stage 2.
    1602: {
        basic_2: {
            after: ['skill_carmine_gleam_damage'],
            note: 'Maintainer-verified in-game: her skill weaves into the Basic chain — Carmine Gleam chains into Basic Attack Stage 2 (undocumented).',
        },
    },

    // Roccia — Intro: "Use [Basic Attack] right after casting this skill to
    // cast [Basic Attack Stage 4]."
    1606: {
        basic_4: {
            after: ['intro'],
            note: 'Intro (Pero, Help) chains directly into Basic Attack Stage 4.',
        },
    },

    // Cantarella — Intro (Ripple): "[Normal Attack] shortly after casting
    // this skill to start the Basic Attack combo from [Basic Attack Stage 3]."
    // (Her Phantom Sting Mirage entry is handled by the ROTATION_RULES entry.)
    1607: {
        basic_3: {
            after: ['intro_ripple'],
            note: 'Intro (Ripple) starts the Basic combo from Stage 3.',
        },
    },

    // Phrolova — both Intros: "[Normal Attack] shortly after casting this
    // skill to cast [Basic Attack Stage 3]"; Dodge Counter → Basic 3; Heavy →
    // Basic 2.
    1608: {
        basic_2: {
            after: ['heavy_heavy_attack'],
            note: 'Heavy Attack chains into Basic Attack Stage 2.',
        },
        basic_3: {
            after: ['intro_suite_of_immortality', 'intro_suite_of_quietus', 'basic_dodge_counter'],
            note: 'Either Intro / Dodge Counter chains into Basic Attack Stage 3.',
        },
    },

    // Suisui — NOT a game mechanic: a data key-naming artifact. The raw kit
    // text names her Stage 2 "Zephyr StanceStage 2" (missing the space present
    // on every other stage, e.g. "Drizzle Stance Stage 2"), so preprocess.mjs's
    // slug lands as `basic_zephyr_stancestage_2` — one word short of matching
    // its `basic_zephyr_stance_{1,3,4}` siblings. The stage-ordering heuristic
    // reads that as an unrelated single-stage family, so Stage 3 warns "Stage 2
    // should come first" even though Stage 2 (the mis-keyed one) was cast right
    // before it. This grant is the family link the key typo breaks, not a
    // Suisui-specific chain rule.
    1110: {
        basic_zephyr_stance_3: {
            after: ['basic_zephyr_stancestage_2'],
            note: 'Basic Attack - Zephyr Stance Stage 2 (mis-keyed as basic_zephyr_stancestage_2) chains into Stage 3.',
        },
    },
});

/** Stage grants for a resonator, or an empty object if none. */
export function stageGrantsForResonator(resonatorId) {
    return STAGE_GRANTS[Number(resonatorId)] ?? {};
}

// =============================================================================
// Swap-in combo entry, keyed by resonator id.
// =============================================================================
//
// MAINTAINER-VERIFIED IN-GAME (2026-07-05), not documented in any kit text or
// community source: when these resonators are swapped in WITHOUT an Intro
// Skill, an automatic Basic Stage 1 fires and the first user-input Basic lands
// at STAGE 3 — i.e. stages 1–2 are effectively pre-seen at rotation start.
// Verified for Yangyang, Verina, Yinlin + spot-checks Roccia, Camellya.
// Explicitly NOT true for Chisa, Aemeath, Denia (they start at Stage 1).
// The auto-Basic-1's damage is NOT modeled as a step (known gap).

export const SWAP_IN_ENTRY = Object.freeze({
    1302: { family: 'basic', preSeen: [1, 2] },   // Yinlin
    1402: { family: 'basic', preSeen: [1, 2] },   // Yangyang
    1503: { family: 'basic', preSeen: [1, 2] },   // Verina
    1603: { family: 'basic', preSeen: [1, 2] },   // Camellya
    1606: { family: 'basic', preSeen: [1, 2] },   // Roccia
});

/** Swap-in entry seeding for a resonator, or null. */
export function swapInEntryForResonator(resonatorId) {
    return SWAP_IN_ENTRY[Number(resonatorId)] ?? null;
}

// =============================================================================
// Curated resource definitions, keyed by resonator id.
// =============================================================================
//
// Minimal per-rotation resource tracking for gates the kit text quantifies
// exactly. Deliberately simple: gains are per-cast constants, spendAll keys
// zero the pool, `cap` clamps. This is validation/gating-grade tracking, not
// full Phase-B gauge simulation (hit-count/off-field income is out of scope).
//
//   { name, channel?, unit?, cap, gains: { skillKey: amount }, spendAll: [skillKey] }
//
// `channel` names the game's own SpecialEnergy channel for this gauge (1–5).
// When it is set, `resourceDefsForResonator(id, dataset)` replaces `cap` with
// the game's declared `SpecialEnergy{channel}Max`, so the number in the sim is
// the number the game ships rather than one read out of kit text. The literal
// `cap` below stays as the offline fallback (a caller with no dataset) and is
// asserted equal to the extracted value by tests/rotation-resources.test.mjs,
// so it cannot silently drift.
//
// `unit` (default 1) is the divisor that reads a channel in the KIT'S OWN
// units. `SpecialEnergy{channel}Max` and a cast's raw magnitude are not
// necessarily already in the number the kit states — Denia's SpecialEnergy2Max
// reads 3, matching "up to 3 Dark Cores" directly, but Aemeath's SpecialEnergy1
// reads 20000 where her kit says "capped at 4 points": the game scales this
// channel internally by 5000 per point. The GCD of a channel's amounts does
// NOT derive the divisor (Aemeath's ch2 grants are 4000/3000/-10000/-20000,
// whose GCD is 1000, but the kit's own stated points — 40/30/100/200 — need
// /100). It takes a second witness: the kit's OWN stated point value on a
// grant whose raw magnitude is already known, cross-checked against at least
// two independent clauses before it is trusted (Aemeath's below has three:
// two grants and the cap itself, all divide evenly by the same number).
//
// What still has to be curated, and why: the channel↔name link, and the gains
// a cast does NOT state.
//
// ~~Income is unreadable and stays curated~~ — that held only while the Buff
// table was undumped. `data/gauge-income.json` (tools/extract/
// extract_gauge_income.py) now reads it: a DT_SkillInfo row's SkillBuff /
// SkillStartBuff / SkillEndBuff resolve to db_buff rows whose GameAttributeID is
// an Energy/SpecialEnergy channel, giving the exact per-cast delta for 50
// resonators. Denia's entry below is filled entirely from it.
//
// The boundary that remains is the CAST: income earned on a HIT lives in
// db_PassiveSkill behind ExtraEffect chains and is not modelled here, which is
// why Changli's Enflamement (1 per True Sight hit) is still hand-written while
// Denia's Intro grant is not. Cross-check a curated `gains` against the
// extraction before trusting it; tests/gauge-income.test.mjs pins the ones the
// game states.

export const RESOURCE_DEFS = Object.freeze({
    // Changli — "Changli can hold up to 4 stacks of Enflamement. Changli obtains
    // 1 stack of Enflamement for every Basic Attack: [True Sight - Conquest] on
    // hit. […] for every Basic Attack: [True Sight - Charge] on hit. Changli
    // obtains 4 stacks of Enflamement for every Resonance Liberation [Radiance
    // of Fealty]." Spent by Heavy Attack [Flaming Sacrifice], which "consumes
    // all stacks of Enflamement" (and requires 4 to cast at all).
    // The two True Sight keys live under `skill_` in autoSkillMap even though
    // the kit text calls them Basic Attacks — the same key spelling her already-
    // curated S2.0 effect override uses.
    1205: [{
        name: 'Enflamement',
        channel: 1,       // SpecialEnergy1Max = 4 in the game's own baseproperty table
        cap: 4,
        gains: {
            skill_true_sight_conquest: 1,
            skill_true_sight_charge: 1,
            liberation: 4,
        },
        spendAll: ['forte_heavy_flaming_sacrifice'],
    }],
    // Sigrika — "After casting [Heavy Attack - Schemata of Runes], gain 50 of
    // [Full Stop], up to 100 points." The Runic variants ARE Schemata casts
    // ("this skill gains the effect of [Runic X]"). Forte Circuit "Learn My
    // True Name": "[Hold Resonance Skill] to consume all [Full Stop]".
    // Denia — the first gauge whose income is READ rather than guessed
    // (data/gauge-income.json, 2026-08-12). Every number below is the game's:
    //   cap 3           SpecialEnergy2Max, matching "Denia can hold up to 3
    //                   [Dark Cores]"
    //   +1 per Intro    rows 1211061/1211062 (her two QTE rows, one per form)
    //                   each grant SpecialEnergy2 +1, matching "Denia obtains 1
    //                   upon casting Intro Skill [It's Been A While!] and Intro
    //                   Skill [Knock Knock]"
    // The spender is the kit's, not the table's: no DT_SkillInfo row spends
    // SpecialEnergy2, so "[Banish - Breakdown Form Stage 2] consumes all [Dark
    // Cores]" remains the source for that one line.
    //
    // What the gauge is FOR: "For each [Dark Core] consumed, the DMG Multiplier
    // of the attack is increased by 150%." The game ships that ladder as damage
    // rows too — 12111052110/…120/…130/…140/…150 are exactly 2.5x/4.0x/5.5x/
    // 7.0x/8.5x her 56.34% display row, i.e. base x (1 + 1.5N) — which is the
    // answer key tests/rotation-resources.test.mjs checks the sim against.
    //
    // A GAUGE DOES NOT NECESSARILY START EMPTY, and this one does not. Her
    // inherent Vestiges of Falsehood: "When Denia engages in combat in
    // Stagecraft Form: restore Dark Cores to 2 if she has fewer than 2 […] This
    // effect can be triggered once every 12s." At S3 it is enhanced to "Upon
    // entering combat, Dark Core and Void Particle are restored to the max",
    // and the SAME node raises the limit to 5 — so cap and start move together,
    // and an S3 build opens on 5/5 (which is what makes her Intro grant, needed
    // at S0, overflow and be wasted at S3).
    //
    // Only the S3 branch is in the data: trigger row 1211700101 (cd 12.0, the
    // enter-combat listener) adds 100% of SpecialEnergy2Max. The base
    // "restore to 2" floor and the 3→5 bump appear nowhere in gauge-income.json
    // — no isCap row exists for her — so those two numbers are the kit's, with
    // the extracted S3 branch as the cross-check that the mechanism is real.
    //
    // ~~MODELLED AT FIGHT START ONLY. The kit's "once every 12s" means a later
    // swap-in can restore the gauge again; the resource model has no swap-in
    // trigger, so a multi-pass team sim refills only on the opening pass.~~
    // It is a CYCLE, not a one-shot: "This effect can be triggered once every
    // 12s" is a rate limit on a passive that re-checks its condition, so it
    // fires at fight start and every 12s of gameTime after. Both extracted rows
    // carry cooldownSeconds 12.0, which is the period. `start` states the same
    // opening level and stays: a refill to a floor is idempotent, so the two
    // agree at t=0 by construction and a test asserts it.
    //
    // ~~The tick is GATED on Stagecraft Form, because the base clause says "When
    // Denia engages in combat in Stagecraft Form".~~ That withheld the whole
    // Breakdown Form branch. The form does not decide WHETHER the passive fires,
    // it decides HOW FAR it refills (maintainer, 2026-09-02): in Stagecraft Form
    // the passive generation stops at 2 Dark Cores, in Breakdown Form it is not
    // limited and fills to the gauge's own cap. The CAP itself is 3 in both
    // forms — the 2 is a floor on this passive, never a second limit.
    //
    // Only the Stagecraft half is in the kit text; the Breakdown half is the
    // maintainer's, and neither appears in gauge-income.json (which carries the
    // S3 addFraction row alone). `refillTo: 'cap'` is written rather than a
    // literal so the S3 cap bump carries into it automatically.
    1211: [{
        name: 'Dark Core',
        channel: 2,       // SpecialEnergy2Max = 3 in the game's own baseproperty table
        cap: 3,
        start: 2,
        // Trigger row 1211700101, cooldownSeconds 12.0, +100% of SpecialEnergy2Max.
        tick: { period: 12, refillTo: 'cap', byState: { 'Stagecraft Form': 2 } },
        chainOverrides: { 3: { cap: 5, start: 5, tick: { byState: {} } } },
        gains: {
            intro_it_s_been_a_while: 1,
            intro_knock_knock: 1,
        },
        spendAll: ['skill_banish_breakdown_form_2'],
    }, {
        // "Denia can hold up to 100 of [Void Particle]." — "Casting Intro Skill
        // [It's Been A While!], Intro Skill [Knock Knock] or Resonance Skill
        // [Phantom Bubble - Stagecraft Form] grants 25 of [Void Particle]."
        // Rows 1211041/1211061/1211062, each +25 on SpecialEnergy1. The same
        // inherent that floors Dark Core floors this one: "restore Void Particle
        // to 20 if she has fewer than 20", and S3 restores it to the max.
        //
        // NOT MODELLED: "While in [Stagecraft Form], dealing damage through
        // [Normal Attack] grants [Void Particle]" is HIT income, and her only
        // extracted trigger row is the enter-combat one — so this gauge fills
        // from casts alone and reads LOW, never high.
        name: 'Void Particle',
        channel: 1,
        cap: 100,
        start: 20,
        // Trigger row 1211700101, cooldownSeconds 12.0, +100% of SpecialEnergy1Max.
        tick: { period: 12, refillTo: 'cap', byState: { 'Stagecraft Form': 20 } },
        chainOverrides: { 3: { start: 100, tick: { byState: {} } } },
        gains: {
            intro_it_s_been_a_while: 25,
            intro_knock_knock: 25,
            skill_phantom_bubble_stagecraft_form: 25,
        },
        spendAll: ['liberation_final_act_breakdown_form'],
    }, {
        // "Denia can hold up to 100 points of [Conformal Charge]." — "Casting
        // Resonance Skill [Banish - Breakdown Form Stage 2] grants 40 of
        // [Conformal Charge]." The grant is row 1211048 (+40 on
        // SpecialEnergy3), whose join is REFUSED, so the KEY here is the kit's
        // while the magnitude and channel are the game's.
        //
        // NOT MODELLED: the [Breakdown Form] Normal Attack / [Beckon] hit
        // income, same lane and same reason as Void Particle above.
        //
        // ONE ROW SPENDS BOTH: 1211053 carries a spendAll on SpecialEnergy1 AND
        // SpecialEnergy3, which is the kit's "When [Conformal Charge] is full,
        // consume all [Conformal Charge] and [Void Particle] to perform this
        // skill" verbatim. Its montage join was wrong — it landed on a
        // forte_heavy per-tick key — and the genre demotion in
        // build-skill-join.mjs resolves it to the liberation key.
        //
        // The GATE is deliberately NOT enforced. Maintainer-confirmed, the only
        // condition is a full Conformal Charge (Void Particle is consumed but
        // never required), but the hit income above is missing, so this gauge
        // reads 40 on her reference rotation where the game has 100. Gating on
        // it would flag a LEGAL rotation as illegal.
        name: 'Conformal Charge',
        channel: 3,
        cap: 100,
        gains: {
            skill_banish_breakdown_form_2: 40,
        },
        spendAll: ['liberation_final_act_breakdown_form'],
    }],
    // Aemeath — her "split Forte bar" is two channels, not one gauge split in
    // two, confirmed by the kit's own text (data/extracted-nanoka/characters/
    // 1210.json): "Resonance Rate is capped at {4} points. Casting Resonance
    // Skill Seraphic Duet recovers {1} point... Casting Resonance Liberation
    // Heavenfall Edict: Overdrive recovers {1} point." / "Synchronization Rate
    // is capped at {200} points. […] Casting Intro Skill [Songs Across the
    // Universe] and [Debut of Meteoric Radiance] recovers {40} points […]
    // Casting Resonance Liberation [Heavenfall Edict: Overdrive] recovers {30}
    // points." Both gauges use `unit: 5000`/`unit: 100` respectively — the raw
    // SpecialEnergy1/2Max both read 20000, and the divisor is confirmed by
    // THREE independent points per channel (a cap and two grants) all dividing
    // evenly to the kit's own stated numbers, not by a bare GCD.
    //
    // "Heavenfall Edict: Finale" — gated on BOTH gauges reaching their limit —
    // is `liberation_heavenfall_edict_finale` (raw row 12101202), which drains
    // BOTH channels in full (-20000/-20000, the game's own full-cap values).
    //
    // NEITHER gauge scales a damage multiplier today (`grep` over her
    // skillNodeEffects: zero `resource` triggers) — both gate CAST AVAILABILITY
    // only ("Enhanced Sync Attack is available", "Resonance Liberation Finisher
    // becomes available"), which the engine does not model as a legality gate
    // yet. This entry is therefore correctness/provenance work: it does not
    // move any damage number today, only what a future legality check or
    // `stackTrigger.resource` clause could read.
    //
    // NOT MODELLED: HIT income ("Dealing damage with Basic Attack - Aemeath,
    // Mid-air Attack, Dodge Counter, […] Sync Strike: Armament Merge and Sync
    // Strike: Call of Dawn recovers Synchronization Rate") is out of the
    // per-cast model by construction (CLAUDE.md, "Gauge income is readable ON
    // A CAST, and only there"). A conditional Charged-II grant gated on being
    // in BOTH Instant Response and Heavenfall Edict: Unbound simultaneously is
    // also excluded — it needs a state gate this module does not evaluate.
    //
    // STILL UNJOINED, and NOT guessed here: raw skill row 12101103
    // ("【技能】合击·降临", montage AM_Skill04_GD — a real, resolved, 7-hit,
    // 4.3s cast) also grants Resonance Rate +1 and spends Synchronization Rate
    // -100 — matching "Casting Resonance Skill Seraphic Duet recovers 1
    // point" too, so it is almost certainly the SAME clause's OTHER trigger.
    // But it has NO skillMap key (none of her autoSkillMap entries cite this
    // montage) and NO damage-table row under its own id prefix — unlike its
    // near-identical sibling 12102103 ("合击·登台"), which DOES join, via a
    // DIFFERENT montage (AM_Skill03), to `forte_heavy_seraphic_duet_bonus_dmg
    // _per_instance`. The two are not the same cast (different montages), so
    // crediting 12101103's grant to that key would be a guess, not a join.
    // This looks like a genuinely missing rotation step (OPEN-ITEMS 39/38),
    // not merely an unattributed gauge grant, and is left out of `gains` for
    // that reason — see OPEN-ITEMS 39 for the full writeup.
    1210: [{
        name: 'Resonance Rate',
        channel: 1,
        unit: 5000,
        cap: 4,
        gains: {
            liberation_heavenfall_edict_overdrive: 1,
        },
        spendAll: ['liberation_heavenfall_edict_finale'],
    }, {
        name: 'Synchronization Rate',
        channel: 2,
        unit: 100,
        cap: 200,
        gains: {
            intro_songs_across_the_universe: 40,
            intro_debut_of_meteoric_radiance: 40,
            liberation_heavenfall_edict_overdrive: 30,
        },
        spendAll: ['liberation_heavenfall_edict_finale'],
    }],
    1412: [{
        name: 'Full Stop',
        cap: 100,
        gains: {
            forte_heavy_schemata_of_runes: 50,
            forte_heavy_runic_chain_whip: 50,
            forte_heavy_runic_outburst: 50,
            forte_heavy_runic_soliskin: 50,
        },
        spendAll: ['forte_heavy_forte_circuit_learn_my_true_name'],
    }],

    // Roccia — "Roccia can hold up to 300 Imagination." (2026-09-21,
    // OPEN-ITEMS 22/36/39, following the Aemeath `unit`-divisor pattern):
    // channel/cap verified against the game's own specialEnergyCaps (300,
    // no divisor needed here — unlike Aemeath's channels, this one is
    // already in kit-native points). Gains: "Casting Resonance Skill
    // [Acrobatic Trick] restores 100 Imagination" is a real cast row
    // (gauge-income.json 1606009, SpecialEnergy1 +100); "Casting Intro Skill
    // [Pero, Help] restores 100 Imagination" has NO row in gauge-income.json
    // (same shape as Denia's hand-curated spenders) so it is curated
    // straight from the kit text. Spend: "consume 100 Imagination to cast
    // Basic Attack [Real Fantasy]" names the WHOLE combo, not each of its
    // three stages, so only the entry key (forte_heavy_1) spends — reading it
    // as a per-stage cost would need 300 banked to complete a chain the kit
    // gates at 100.
    //
    // NOT modelled: the relaunch clause ("When Roccia lands after Stage 1 and
    // Stage 2 attacks with over 100 Imagination, she will... activate [Beyond
    // Imagination]" — which is what forte_heavy_1/2/3's needsStateModel entry
    // in data/timing-overrides.json is asking about) depends on Imagination
    // regenerated by NORMAL ATTACK HITS during the combo, which is HIT income
    // and out of this per-cast model by construction (CLAUDE.md, "Gauge
    // income is readable ON A CAST, and only there"). So the sim's own
    // tracked level after forte_heavy_1's spend reads LOW (understated, the
    // safe direction) rather than crediting a relaunch the model cannot see —
    // the timing-variant WIRING itself is not done here.
    // Luuk Herssen — "Endnotes on the Endgame" (2026-10-02, OPEN-ITEMS 2). The
    // Forte Circuit states the whole gauge in its own section, which is why the
    // blocker recorded on the S6.1 override — "Stack source is Tune Break DMG
    // dealt by teammates - unresolvable until OPEN-ITEMS #7 wires
    // computeTuneBreakDamage" — was WRONG on both halves: the source is not Tune
    // Break and the wiring it waited on is not needed. Verbatim:
    //   "Casting any form of [Aureole of Execution] grants 1 of [Endnotes on
    //    the Endgame] and switches [Aureole of Execution] to the next form in
    //    sequence."
    //   "Increase the DMG Multiplier of Resonance Liberation [Rewritten in
    //    Winter's Margins] by 25%, stacking up to 3 times. Casting [Rewritten in
    //    Winter's Margins] or switching to another Resonator removes all
    //    stacks."
    // Three FORMS grant, and only those three: Golden Reflux is the base
    // Resonance Skill that Aureole REPLACES, while Golden Impale and Ichor
    // Deposit are follow-ups a form spawns, not forms of it.
    //
    // NO `channel`, deliberately. His specialEnergyCaps are
    // {1: 30000, 2: 300, 3: 150, 4: 6000, 5: 10000} and none reads 3 — two of
    // them reach it under a divisor (ch2 at unit 100, ch3 at unit 50), and
    // gauge-income.json holds not one SpecialEnergy row for him (his only cast
    // row is the Liberation's Resonance-energy spendAll), so there is no raw
    // magnitude to cross-check a divisor against. That is exactly the second
    // witness the docblock above requires before a `unit` is trusted, so the
    // channel stays unclaimed and `cap` is the kit's own number — which the kit
    // states TWICE independently ("stacking up to 3 times" in the Forte, and
    // S6's "40% DMG Bonus, up to 120%" = 3). Same shape as Sigrika's Full Stop.
    //
    // "switching to another Resonator removes all stacks" is NOT modelled as a
    // cross-segment clear, and cannot bite today: a gauge is carried between
    // segments by design (CLAUDE.md, "A gauge belongs to the CHARACTER"), but
    // his rotation ENDS on the Liberation that spends all of it, so every
    // carry-out is already 0. A rotation that ended holding stacks would carry
    // them over a swap the game clears — worth stating, not worth a mechanism
    // no shipped rotation exercises.
    1510: [{
        name: 'Endnotes on the Endgame',
        cap: 3,
        gains: {
            skill_aureole_of_execution_ring: 1,
            skill_aureole_of_execution_breach: 1,
            skill_aureole_of_execution_glare: 1,
        },
        spendAll: ['liberation'],
    }],

    1606: [{
        name: 'Imagination',
        channel: 1,       // SpecialEnergy1Max = 300 in the game's own baseproperty table
        cap: 300,
        gains: {
            skill: 100,
            intro: 100,
        },
        spend: {
            forte_heavy_1: 100,
        },
    }],
});

/**
 * Resource definitions for a resonator, or an empty array.
 *
 * Pass the dataset to resolve each gauge's cap from the game's own
 * `SpecialEnergy{channel}Max` (stamped onto the resonator by preprocess.mjs
 * from the BinData dump) instead of the curated literal. Without it the
 * literal stands — same number today, guarded by a test.
 *
 * Pass the build's chain level to apply `chainOverrides`. A Resonance Chain
 * node can move a gauge's cap AND the level it starts a fight on, and Denia's
 * S3 moves both at once — resolving the cap from the game's base table alone
 * holds an S3 build to 3 where the kit gives it 5.
 *
 * @param {number|string} resonatorId
 * @param {object|null} [dataset]
 * @param {number} [chainLevel] — build.chain (0..6)
 */
/**
 * Skills that only EXIST once a Resonance Chain node creates them.
 *
 * A sequence node can replace a Forte/Resonance Skill outright: Lupa S6 says
 * "Forte Circuit Dance With the Wolf is replaced with Dance With the Wolf:
 * Climax". The game ships BOTH as damage rows (12070007001 and 12070007002),
 * so both resolve as ordinary skill keys and nothing stopped a rotation from
 * casting the S6 one on an S0 build — her own reference rotation does exactly
 * that, and the replacement is worth 1.35x the skill it replaces.
 *
 * `fallback` is what the same button produces below `minChain`, which is what
 * makes SUBSTITUTION the faithful model rather than dropping the step: the
 * player presses the same input either way and the game decides which move
 * comes out. Dropping it would understate by removing a cast that happens.
 *
 * Only entries whose BOTH keys exist may be listed — a replacement the dataset
 * has no row for (Qiuyuan S3's Straw Cape in Drizzly Rain, Camellya S6's
 * Perennial) is a missing-damage gap, not something this can express.
 */
export const CHAIN_LOCKED_SKILLS = Object.freeze({
    // Lupa S6: "Forte Circuit Dance With the Wolf is replaced with Dance With
    // the Wolf: Climax." Measured on her reference rotation: casting Climax at
    // S0 inflated the whole rotation 8.13%, and at S6 Climax is worth 61% more
    // than the base skill, so neither key is right for both builds.
    1207: {
        forte_heavy_dance_with_the_wolf_climax: {
            minChain: 6,
            fallback: 'forte_heavy_dance_with_the_wolf',
            quote: 'Forte Circuit Dance With the Wolf is replaced with Dance With the Wolf: Climax.',
        },
    },
});

/**
 * Swap any chain-locked step a build has not unlocked for what the same input
 * actually produces at that chain level.
 *
 * Returns the rotation unchanged (the SAME array) when nothing is locked, so
 * the common path allocates nothing and callers can compare by identity.
 *
 * @param {string[]} rotation
 * @param {number|string} resonatorId
 * @param {number} chainLevel
 * @returns {{ rotation: string[], substitutions: Array<{from: string, to: string, minChain: number}> }}
 */
export function resolveChainLockedRotation(rotation, resonatorId, chainLevel = 0) {
    const locks = CHAIN_LOCKED_SKILLS[Number(resonatorId)];
    if (!locks || !Array.isArray(rotation)) return { rotation, substitutions: [] };
    const substitutions = [];
    const resolved = rotation.map(key => {
        const lock = locks[key];
        if (!lock || (chainLevel ?? 0) >= lock.minChain) return key;
        substitutions.push({ from: key, to: lock.fallback, minChain: lock.minChain });
        return lock.fallback;
    });
    return substitutions.length ? { rotation: resolved, substitutions } : { rotation, substitutions };
}

export function resourceDefsForResonator(resonatorId, dataset = null, chainLevel = 0) {
    const defs = RESOURCE_DEFS[Number(resonatorId)] ?? [];
    if (defs.length === 0) return defs;
    const caps = dataset?.resonators?.find(entry => entry.id === Number(resonatorId))?.specialEnergyCaps ?? null;
    return defs.map(def => {
        const chained = chainOverrideFor(def.chainOverrides, chainLevel);
        const rawGameCap = def.channel != null ? caps?.[def.channel] ?? null : null;
        const gameCap = rawGameCap != null ? rawGameCap / (def.unit ?? 1) : null;
        // A chain node outranks the game's BASE table, which is what it edits.
        const cap = chained?.cap ?? gameCap ?? def.cap;
        const start = chained?.start ?? def.start;
        // A chain node EDITS a tick rather than restating it: Denia's S3 moves
        // only `refillTo`, and the period stays the kit's 12s. Merging keeps a
        // partial override partial, so a node that changes the ceiling cannot
        // silently drop the state gate or the period with it.
        const tick = chained?.tick ? { ...def.tick, ...chained.tick } : def.tick;
        if (cap === def.cap && start === def.start && tick === def.tick) return def;
        const resolved = { ...def, cap };
        if (start != null) resolved.start = start;
        if (tick) resolved.tick = tick;
        return resolved;
    });
}

/**
 * The chain override in force at a build's chain level, or null.
 *
 * The highest key at or below the build's level SUPERSEDES the rest — the same
 * rule chain-extra-hits.mjs applies within a `family`, and for the same reason:
 * a node that restates a gauge's limit replaces the earlier statement of it
 * rather than adding to it.
 *
 * @param {Object<string, {cap?: number, start?: number}>|undefined} overrides
 * @param {number} chainLevel
 */
function chainOverrideFor(overrides, chainLevel) {
    if (!overrides) return null;
    let best = null;
    let bestLevel = -1;
    for (const [levelKey, override] of Object.entries(overrides)) {
        const level = Number(levelKey);
        if (level <= chainLevel && level > bestLevel) {
            bestLevel = level;
            best = override;
        }
    }
    return best;
}
